package ProtocolBuffers::PP::Generator;
use strict;
use warnings;
use ProtocolBuffers::PP::Types qw(
    TYPE_DOUBLE TYPE_FLOAT TYPE_INT64 TYPE_UINT64 TYPE_INT32
    TYPE_FIXED64 TYPE_FIXED32 TYPE_BOOL TYPE_STRING TYPE_GROUP
    TYPE_MESSAGE TYPE_BYTES TYPE_UINT32 TYPE_ENUM TYPE_SFIXED32
    TYPE_SFIXED64 TYPE_SINT32 TYPE_SINT64
    LABEL_OPTIONAL LABEL_REQUIRED LABEL_REPEATED
);

sub new {
    my ($class, %args) = @_;
    return bless {
        request => $args{request},
        type_registry => {},      # full_name -> { kind => 'message'|'enum', descriptor => ..., perl_class => ... }
        file_map => {},           # proto filename -> FileDescriptorProto
    }, $class;
}

sub generate {
    my ($self) = @_;
    my $request = $self->{request};

    # Build file map
    for my $file (@{$request->{proto_file} || []}) {
        $self->{file_map}{$file->{name}} = $file;
    }

    # Build type registry from all proto files
    for my $file (@{$request->{proto_file} || []}) {
        my $pkg = $file->{'package'} || '';
        $self->_register_types($file, $pkg);
    }

    # Generate code for requested files
    my %to_generate = map { $_ => 1 } @{$request->{file_to_generate} || []};
    my @output_files;

    for my $file (@{$request->{proto_file} || []}) {
        next unless $to_generate{$file->{name}};
        my $code = $self->_generate_file($file);
        my $path = $self->_proto_to_pm_path($file->{name}, $file->{'package'});
        push @output_files, {
            name => $path,
            content => $code,
        };
    }

    return {
        supported_features => 1,  # FEATURE_PROTO3_OPTIONAL
        file => \@output_files,
    };
}

sub _register_types {
    my ($self, $file, $pkg) = @_;
    my $syntax = $file->{syntax} || 'proto2';

    for my $msg (@{$file->{message_type} || []}) {
        my $full = $pkg ? "$pkg.$msg->{name}" : $msg->{name};
        $self->_register_message($msg, $full, $syntax);
    }
    for my $enum (@{$file->{enum_type} || []}) {
        my $full = $pkg ? "$pkg.$enum->{name}" : $enum->{name};
        my $perl_class = _full_name_to_perl_class($full);
        $self->{type_registry}{".$full"} = {
            kind => 'enum',
            descriptor => $enum,
            perl_class => $perl_class,
        };
    }
}

sub _register_message {
    my ($self, $msg, $full, $syntax) = @_;
    my $perl_class = _full_name_to_perl_class($full);
    $self->{type_registry}{".$full"} = {
        kind => 'message',
        descriptor => $msg,
        perl_class => $perl_class,
        syntax => $syntax,
    };

    for my $nested (@{$msg->{nested_type} || []}) {
        $self->_register_message($nested, "$full.$nested->{name}", $syntax);
    }
    for my $enum (@{$msg->{enum_type} || []}) {
        my $enum_full = "$full.$enum->{name}";
        my $enum_class = _full_name_to_perl_class($enum_full);
        $self->{type_registry}{".$enum_full"} = {
            kind => 'enum',
            descriptor => $enum,
            perl_class => $enum_class,
        };
    }
}

sub _generate_file {
    my ($self, $file) = @_;
    my $syntax = $file->{syntax} || 'proto2';
    my $pkg = $file->{'package'} || '';
    my $code = '';

    $code .= "# Generated by protoc-gen-perl. DO NOT EDIT.\n";
    $code .= "# Source: $file->{name}\n\n";

    # Generate enums at file level
    for my $enum (@{$file->{enum_type} || []}) {
        my $full = $pkg ? "$pkg.$enum->{name}" : $enum->{name};
        $code .= $self->_generate_enum($enum, $full);
    }

    # Generate messages
    for my $msg (@{$file->{message_type} || []}) {
        my $full = $pkg ? "$pkg.$msg->{name}" : $msg->{name};
        $code .= $self->_generate_message($msg, $full, $syntax);
    }

    # Generate service client stubs
    for my $svc (@{$file->{service} || []}) {
        my $full = $pkg ? "$pkg.$svc->{name}" : $svc->{name};
        $code .= $self->_generate_service($svc, $full, $pkg);
    }

    $code .= "1;\n";
    return $code;
}

sub _generate_enum {
    my ($self, $enum, $full_name) = @_;
    my $perl_class = _full_name_to_perl_class($full_name);
    my $code = "{\npackage $perl_class;\n";
    $code .= "use strict;\nuse warnings;\n";
    $code .= "use parent 'ProtocolBuffers::Generated::Enum';\n\n";

    $code .= "use constant {\n";
    for my $val (@{$enum->{value} || []}) {
        $code .= "    $val->{name} => $val->{number},\n";
    }
    $code .= "};\n\n";

    $code .= "my \%VALUES = (\n";
    for my $val (@{$enum->{value} || []}) {
        $code .= "    '$val->{name}' => $val->{number},\n";
    }
    $code .= ");\n\n";

    $code .= "my \%NAMES = reverse \%VALUES;\n\n";

    $code .= "sub _values { \\%VALUES }\n";
    $code .= "sub name_for { my (\$class, \$num) = \@_; return \$NAMES{\$num} }\n";
    $code .= "sub value_for { my (\$class, \$name) = \@_; return \$VALUES{\$name} }\n\n";
    $code .= "} # end package $perl_class\n\n";

    return $code;
}

sub _generate_message {
    my ($self, $msg, $full_name, $syntax) = @_;
    my $perl_class = _full_name_to_perl_class($full_name);
    my $code = '';

    # Generate nested enums first
    for my $enum (@{$msg->{enum_type} || []}) {
        my $enum_full = "$full_name.$enum->{name}";
        $code .= $self->_generate_enum($enum, $enum_full);
    }

    # Generate nested messages
    for my $nested (@{$msg->{nested_type} || []}) {
        my $nested_full = "$full_name.$nested->{name}";
        $code .= $self->_generate_message($nested, $nested_full, $syntax);
    }

    # Check if this is a map entry
    my $is_map_entry = $msg->{options} && $msg->{options}{map_entry} ? 1 : 0;

    # Build field descriptors
    my @oneofs;
    for my $oneof (@{$msg->{oneof_decl} || []}) {
        push @oneofs, { name => $oneof->{name}, fields => [] };
    }

    $code .= "{\npackage $perl_class;\n";
    $code .= "use strict;\nuse warnings;\n";
    $code .= "use parent 'ProtocolBuffers::Generated::Message';\n";
    $code .= "use ProtocolBuffers::PP::Types;\n\n";

    # Build the descriptor hash as code
    $code .= "my \$DESCRIPTOR;\n";
    $code .= "sub __DESCRIPTOR__ { _build_descriptor() unless \$DESCRIPTOR; return \$DESCRIPTOR }\n\n";

    # Lazy descriptor builder to handle forward references
    $code .= "sub _build_descriptor {\n";
    $code .= "    return \$DESCRIPTOR if \$DESCRIPTOR;\n";
    $code .= "    \$DESCRIPTOR = {\n";
    $code .= "        full_name => " . _quote($full_name) . ",\n";
    $code .= "        syntax => " . _quote($syntax) . ",\n";
    $code .= "        _class => " . _quote($perl_class) . ",\n";
    $code .= "        is_map_entry => $is_map_entry,\n";
    $code .= "        fields => {},\n";
    $code .= "        fields_by_name => {},\n";
    $code .= "        fields_by_json_name => {},\n";
    $code .= "        oneofs => [],\n";
    $code .= "    };\n\n";

    # Add oneofs
    for my $i (0 .. $#oneofs) {
        my $oneof = $msg->{oneof_decl}[$i];
        $code .= "    push \@{\$DESCRIPTOR->{oneofs}}, { name => " . _quote($oneof->{name}) . ", fields => [] };\n";
    }

    # Add fields
    for my $field (@{$msg->{field} || []}) {
        my $fn = $field->{number};
        my $name = $field->{name};
        my $json_name = $field->{json_name} || _to_json_name($name);
        my $type = $field->{type};
        my $label = $field->{label} || LABEL_OPTIONAL;
        my $oneof_idx = $field->{oneof_index};
        my $proto3_opt = $field->{proto3_optional} ? 1 : 0;

        # Determine packed
        my $packed = 0;
        if ($field->{options} && defined $field->{options}{packed}) {
            $packed = $field->{options}{packed} ? 1 : 0;
        } elsif ($syntax eq 'proto3' && $label == LABEL_REPEATED && _is_packable_type($type)) {
            $packed = 1;  # proto3 default packed
        }

        $code .= "    \$DESCRIPTOR->{fields}{$fn} = {\n";
        $code .= "        name => " . _quote($name) . ",\n";
        $code .= "        json_name => " . _quote($json_name) . ",\n";
        $code .= "        number => $fn,\n";
        $code .= "        type => $type,\n";
        $code .= "        label => $label,\n";
        $code .= "        packed => $packed,\n";
        if (defined $oneof_idx && !$proto3_opt) {
            $code .= "        oneof_index => $oneof_idx,\n";
        } elsif ($proto3_opt) {
            $code .= "        oneof_index => $oneof_idx,\n";
            $code .= "        proto3_optional => 1,\n";
        } else {
            $code .= "        oneof_index => undef,\n";
        }

        # Default value for proto2
        if (defined $field->{default_value} && $field->{default_value} ne '') {
            $code .= "        default_value => " . _quote($field->{default_value}) . ",\n";
        }

        # Type references
        if ($type == TYPE_MESSAGE || $type == TYPE_GROUP) {
            my $type_name = $field->{type_name};
            if ($type_name) {
                my $ref_info = $self->{type_registry}{$type_name};
                if ($ref_info && $ref_info->{kind} eq 'message') {
                    my $ref_class = $ref_info->{perl_class};
                    $code .= "        message_class => " . _quote($ref_class) . ",\n";
                    # Check if it's a map entry
                    my $ref_msg = $ref_info->{descriptor};
                    if ($ref_msg->{options} && $ref_msg->{options}{map_entry}) {
                        $code .= $self->_generate_map_entry($ref_msg, $type_name);
                    }
                }
            }
        } elsif ($type == TYPE_ENUM) {
            my $type_name = $field->{type_name};
            if ($type_name) {
                my $ref_info = $self->{type_registry}{$type_name};
                if ($ref_info) {
                    $code .= "        enum_class => " . _quote($ref_info->{perl_class}) . ",\n";
                }
            }
        }

        $code .= "    };\n";
        $code .= "    \$DESCRIPTOR->{fields_by_name}{" . _quote($name) . "} = $fn;\n";
        $code .= "    \$DESCRIPTOR->{fields_by_json_name}{" . _quote($json_name) . "} = $fn;\n";

        # Track oneof members
        if (defined $oneof_idx) {
            $code .= "    push \@{\$DESCRIPTOR->{oneofs}[$oneof_idx]{fields}}, $fn;\n";
        }
    }

    # Resolve message_descriptor references (lazy)
    $code .= "\n    # Resolve message_descriptor references\n";
    for my $field (@{$msg->{field} || []}) {
        my $fn = $field->{number};
        my $type = $field->{type};
        if ($type == TYPE_MESSAGE || $type == TYPE_GROUP) {
            my $type_name = $field->{type_name};
            if ($type_name) {
                my $ref_info = $self->{type_registry}{$type_name};
                if ($ref_info && $ref_info->{kind} eq 'message') {
                    my $ref_class = $ref_info->{perl_class};
                    $code .= "    \$DESCRIPTOR->{fields}{$fn}{message_descriptor} = ${ref_class}->__DESCRIPTOR__;\n";

                    # If it's a map entry, also resolve value_message_descriptor
                    my $ref_msg = $ref_info->{descriptor};
                    if ($ref_msg->{options} && $ref_msg->{options}{map_entry}) {
                        # Find the value field (field 2) type
                        for my $vf (@{$ref_msg->{field} || []}) {
                            if ($vf->{number} == 2 && ($vf->{type} == TYPE_MESSAGE || $vf->{type} == TYPE_ENUM)) {
                                my $vtn = $vf->{type_name};
                                my $vri = $self->{type_registry}{$vtn};
                                if ($vri && $vri->{kind} eq 'message') {
                                    $code .= "    \$DESCRIPTOR->{fields}{$fn}{map_entry}{value_message_descriptor} = $vri->{perl_class}->__DESCRIPTOR__;\n";
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    $code .= "    return \$DESCRIPTOR;\n";
    $code .= "}\n\n";

    # Generate accessors
    for my $field (@{$msg->{field} || []}) {
        my $name = $field->{name};
        my $fn = $field->{number};
        my $oneof_idx = $field->{oneof_index};

        # Getter
        $code .= "sub $name {\n";
        $code .= "    my (\$self, \$value) = \@_;\n";
        $code .= "    if (\@_ > 1) {\n";
        if (defined $oneof_idx) {
            # Clear other oneof members
            $code .= "        my \$desc = \$self->__DESCRIPTOR__;\n";
            $code .= "        my \$oneof = \$desc->{oneofs}[$oneof_idx];\n";
            $code .= "        for my \$ofn (\@{\$oneof->{fields}}) {\n";
            $code .= "            next if \$ofn == $fn;\n";
            $code .= "            my \$ofd = \$desc->{fields}{\$ofn};\n";
            $code .= "            \$self->{\$ofd->{name}} = undef;\n";
            $code .= "        }\n";
            $code .= "        \$self->{_oneof_case} ||= {};\n";
            $code .= "        \$self->{_oneof_case}{$oneof_idx} = $fn;\n";
        }
        $code .= "        \$self->{" . _quote($name) . "} = \$value;\n";
        $code .= "    }\n";
        $code .= "    return \$self->{" . _quote($name) . "};\n";
        $code .= "}\n\n";
    }

    $code .= "} # end package $perl_class\n\n";

    return $code;
}

sub _generate_service {
    my ($self, $svc, $full_name, $package) = @_;
    my $perl_class = _full_name_to_perl_class($full_name);
    my $client_class = "${perl_class}::Client";

    my $code = "{\npackage $client_class;\n";
    $code .= "use strict;\nuse warnings;\n\n";

    $code .= "sub new {\n";
    $code .= "    my (\$class, \%args) = \@_;\n";
    $code .= "    return bless { channel => \$args{channel} }, \$class;\n";
    $code .= "}\n\n";

    for my $method (@{$svc->{method} || []}) {
        my $name   = $method->{name};
        my $cs     = $method->{client_streaming} ? 1 : 0;
        my $ss     = $method->{server_streaming} ? 1 : 0;
        my $path   = "/$package.$svc->{name}/$name";
        # Convert dotted package to slash-separated
        $path =~ s/\./\//g while $path =~ /\./;
        # Actually gRPC path uses dots: /package.Service/Method
        $path = "/$package.$svc->{name}/$name";

        my $rpc_type;
        if (!$cs && !$ss) {
            $rpc_type = 'unary';
        } elsif (!$cs && $ss) {
            $rpc_type = 'server_stream';
        } elsif ($cs && !$ss) {
            $rpc_type = 'client_stream';
        } else {
            $rpc_type = 'bidi_stream';
        }

        $code .= "sub $name {\n";
        $code .= "    my (\$self, \$request, \%opts) = \@_;\n";
        $code .= "    return \$self->{channel}->$rpc_type(\n";
        $code .= "        " . _quote($path) . ",\n";
        $code .= "        \$request,\n";
        $code .= "        \%opts,\n";
        $code .= "    );\n";
        $code .= "}\n\n";
    }

    $code .= "} # end package $client_class\n\n";
    return $code;
}

sub _generate_map_entry {
    my ($self, $msg, $type_name) = @_;
    my $code = "        map_entry => {\n";

    my ($key_field, $val_field);
    for my $f (@{$msg->{field} || []}) {
        $key_field = $f if $f->{number} == 1;
        $val_field = $f if $f->{number} == 2;
    }

    $code .= "            key_type => $key_field->{type},\n" if $key_field;
    $code .= "            value_type => $val_field->{type},\n" if $val_field;

    if ($val_field && $val_field->{type} == TYPE_ENUM && $val_field->{type_name}) {
        my $ref = $self->{type_registry}{$val_field->{type_name}};
        $code .= "            value_enum_class => " . _quote($ref->{perl_class}) . ",\n" if $ref;
    }

    $code .= "        },\n";
    return $code;
}

sub _proto_to_pm_path {
    my ($self, $proto_name, $package) = @_;
    # foo/bar.proto with package foo.bar -> Foo/Bar.pm
    # Use the proto filename to derive the path
    my $path = $proto_name;
    $path =~ s/\.proto$//;
    # Convert path segments to title case
    my @parts = split m{/}, $path;
    @parts = map { _title_case($_) } @parts;
    return join('/', @parts) . '.pm';
}

sub _full_name_to_perl_class {
    my ($full_name) = @_;
    # foo.bar.BazQux -> Foo::Bar::BazQux
    my @parts = split /\./, $full_name;
    @parts = map { _title_case($_) } @parts;
    return join('::', @parts);
}

sub _title_case {
    my ($s) = @_;
    # Only capitalize the first letter, preserve the rest
    # e.g., "protobuf" -> "Protobuf", "TestAllTypes" -> "TestAllTypes"
    return ucfirst($s);
}

sub _to_json_name {
    my ($name) = @_;
    # Convert snake_case to lowerCamelCase
    my @parts = split /_/, $name;
    return $parts[0] . join('', map { ucfirst($_) } @parts[1..$#parts]);
}

sub _is_packable_type {
    my ($type) = @_;
    return 0 if $type == TYPE_STRING;
    return 0 if $type == TYPE_BYTES;
    return 0 if $type == TYPE_MESSAGE;
    return 0 if $type == TYPE_GROUP;
    return 1;
}

sub _quote {
    my ($s) = @_;
    return 'undef' unless defined $s;
    $s =~ s/\\/\\\\/g;
    $s =~ s/'/\\'/g;
    return "'$s'";
}

1;
