# Generated by protoc-gen-perl. DO NOT EDIT.
# Source: google/protobuf/any.proto

{
package Google::Protobuf::Any;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'google.protobuf.Any',
        syntax => 'proto3',
        _class => 'Google::Protobuf::Any',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'type_url',
        json_name => 'typeUrl',
        number => 1,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'type_url'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'typeUrl'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'value',
        json_name => 'value',
        number => 2,
        type => 12,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'value'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'value'} = 2;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub type_url {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'type_url'} = $value;
    }
    return $self->{'type_url'};
}

sub value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'value'} = $value;
    }
    return $self->{'value'};
}

} # end package Google::Protobuf::Any

1;
