# Generated by protoc-gen-perl. DO NOT EDIT.
# Source: google/protobuf/field_mask.proto

{
package Google::Protobuf::FieldMask;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'google.protobuf.FieldMask',
        syntax => 'proto3',
        _class => 'Google::Protobuf::FieldMask',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'paths',
        json_name => 'paths',
        number => 1,
        type => 9,
        label => 3,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'paths'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'paths'} = 1;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub paths {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'paths'} = $value;
    }
    return $self->{'paths'};
}

} # end package Google::Protobuf::FieldMask

1;
