# Generated by protoc-gen-perl. DO NOT EDIT.
# Source: google/protobuf/struct.proto

{
package Google::Protobuf::NullValue;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Enum';

use constant {
    NULL_VALUE => 0,
};

my %VALUES = (
    'NULL_VALUE' => 0,
);

my %NAMES = reverse %VALUES;

sub _values { \%VALUES }
sub name_for { my ($class, $num) = @_; return $NAMES{$num} }
sub value_for { my ($class, $name) = @_; return $VALUES{$name} }

} # end package Google::Protobuf::NullValue

{
package Google::Protobuf::Struct::FieldsEntry;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'google.protobuf.Struct.FieldsEntry',
        syntax => 'proto3',
        _class => 'Google::Protobuf::Struct::FieldsEntry',
        is_map_entry => 1,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'key',
        json_name => 'key',
        number => 1,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'key'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'key'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'value',
        json_name => 'value',
        number => 2,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Google::Protobuf::Value',
    };
    $DESCRIPTOR->{fields_by_name}{'value'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'value'} = 2;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{2}{message_descriptor} = Google::Protobuf::Value->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub key {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'key'} = $value;
    }
    return $self->{'key'};
}

sub value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'value'} = $value;
    }
    return $self->{'value'};
}

} # end package Google::Protobuf::Struct::FieldsEntry

{
package Google::Protobuf::Struct;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'google.protobuf.Struct',
        syntax => 'proto3',
        _class => 'Google::Protobuf::Struct',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'fields',
        json_name => 'fields',
        number => 1,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Google::Protobuf::Struct::FieldsEntry',
        map_entry => {
            key_type => 9,
            value_type => 11,
        },
    };
    $DESCRIPTOR->{fields_by_name}{'fields'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'fields'} = 1;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{1}{message_descriptor} = Google::Protobuf::Struct::FieldsEntry->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{1}{map_entry}{value_message_descriptor} = Google::Protobuf::Value->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub fields {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'fields'} = $value;
    }
    return $self->{'fields'};
}

} # end package Google::Protobuf::Struct

{
package Google::Protobuf::Value;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'google.protobuf.Value',
        syntax => 'proto3',
        _class => 'Google::Protobuf::Value',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    push @{$DESCRIPTOR->{oneofs}}, { name => 'kind', fields => [] };
    $DESCRIPTOR->{fields}{1} = {
        name => 'null_value',
        json_name => 'nullValue',
        number => 1,
        type => 14,
        label => 1,
        packed => 0,
        oneof_index => 0,
        enum_class => 'Google::Protobuf::NullValue',
    };
    $DESCRIPTOR->{fields_by_name}{'null_value'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'nullValue'} = 1;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'number_value',
        json_name => 'numberValue',
        number => 2,
        type => 1,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'number_value'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'numberValue'} = 2;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 2;
    $DESCRIPTOR->{fields}{3} = {
        name => 'string_value',
        json_name => 'stringValue',
        number => 3,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'string_value'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'stringValue'} = 3;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 3;
    $DESCRIPTOR->{fields}{4} = {
        name => 'bool_value',
        json_name => 'boolValue',
        number => 4,
        type => 8,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'bool_value'} = 4;
    $DESCRIPTOR->{fields_by_json_name}{'boolValue'} = 4;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 4;
    $DESCRIPTOR->{fields}{5} = {
        name => 'struct_value',
        json_name => 'structValue',
        number => 5,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Google::Protobuf::Struct',
    };
    $DESCRIPTOR->{fields_by_name}{'struct_value'} = 5;
    $DESCRIPTOR->{fields_by_json_name}{'structValue'} = 5;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 5;
    $DESCRIPTOR->{fields}{6} = {
        name => 'list_value',
        json_name => 'listValue',
        number => 6,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Google::Protobuf::ListValue',
    };
    $DESCRIPTOR->{fields_by_name}{'list_value'} = 6;
    $DESCRIPTOR->{fields_by_json_name}{'listValue'} = 6;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 6;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{5}{message_descriptor} = Google::Protobuf::Struct->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{6}{message_descriptor} = Google::Protobuf::ListValue->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub null_value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 1;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 1;
        $self->{'null_value'} = $value;
    }
    return $self->{'null_value'};
}

sub number_value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 2;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 2;
        $self->{'number_value'} = $value;
    }
    return $self->{'number_value'};
}

sub string_value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 3;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 3;
        $self->{'string_value'} = $value;
    }
    return $self->{'string_value'};
}

sub bool_value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 4;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 4;
        $self->{'bool_value'} = $value;
    }
    return $self->{'bool_value'};
}

sub struct_value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 5;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 5;
        $self->{'struct_value'} = $value;
    }
    return $self->{'struct_value'};
}

sub list_value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 6;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 6;
        $self->{'list_value'} = $value;
    }
    return $self->{'list_value'};
}

} # end package Google::Protobuf::Value

{
package Google::Protobuf::ListValue;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'google.protobuf.ListValue',
        syntax => 'proto3',
        _class => 'Google::Protobuf::ListValue',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'values',
        json_name => 'values',
        number => 1,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Google::Protobuf::Value',
    };
    $DESCRIPTOR->{fields_by_name}{'values'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'values'} = 1;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{1}{message_descriptor} = Google::Protobuf::Value->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub values {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'values'} = $value;
    }
    return $self->{'values'};
}

} # end package Google::Protobuf::ListValue

1;
