# Generated by protoc-gen-perl. DO NOT EDIT.
# Source: google/protobuf/timestamp.proto

{
package Google::Protobuf::Timestamp;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'google.protobuf.Timestamp',
        syntax => 'proto3',
        _class => 'Google::Protobuf::Timestamp',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'seconds',
        json_name => 'seconds',
        number => 1,
        type => 3,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'seconds'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'seconds'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'nanos',
        json_name => 'nanos',
        number => 2,
        type => 5,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'nanos'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'nanos'} = 2;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub seconds {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'seconds'} = $value;
    }
    return $self->{'seconds'};
}

sub nanos {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'nanos'} = $value;
    }
    return $self->{'nanos'};
}

} # end package Google::Protobuf::Timestamp

1;
