# Generated by protoc-gen-perl. DO NOT EDIT.
# Source: google/protobuf/wrappers.proto

{
package Google::Protobuf::DoubleValue;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'google.protobuf.DoubleValue',
        syntax => 'proto3',
        _class => 'Google::Protobuf::DoubleValue',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'value',
        json_name => 'value',
        number => 1,
        type => 1,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'value'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'value'} = 1;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'value'} = $value;
    }
    return $self->{'value'};
}

} # end package Google::Protobuf::DoubleValue

{
package Google::Protobuf::FloatValue;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'google.protobuf.FloatValue',
        syntax => 'proto3',
        _class => 'Google::Protobuf::FloatValue',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'value',
        json_name => 'value',
        number => 1,
        type => 2,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'value'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'value'} = 1;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'value'} = $value;
    }
    return $self->{'value'};
}

} # end package Google::Protobuf::FloatValue

{
package Google::Protobuf::Int64Value;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'google.protobuf.Int64Value',
        syntax => 'proto3',
        _class => 'Google::Protobuf::Int64Value',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'value',
        json_name => 'value',
        number => 1,
        type => 3,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'value'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'value'} = 1;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'value'} = $value;
    }
    return $self->{'value'};
}

} # end package Google::Protobuf::Int64Value

{
package Google::Protobuf::UInt64Value;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'google.protobuf.UInt64Value',
        syntax => 'proto3',
        _class => 'Google::Protobuf::UInt64Value',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'value',
        json_name => 'value',
        number => 1,
        type => 4,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'value'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'value'} = 1;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'value'} = $value;
    }
    return $self->{'value'};
}

} # end package Google::Protobuf::UInt64Value

{
package Google::Protobuf::Int32Value;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'google.protobuf.Int32Value',
        syntax => 'proto3',
        _class => 'Google::Protobuf::Int32Value',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'value',
        json_name => 'value',
        number => 1,
        type => 5,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'value'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'value'} = 1;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'value'} = $value;
    }
    return $self->{'value'};
}

} # end package Google::Protobuf::Int32Value

{
package Google::Protobuf::UInt32Value;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'google.protobuf.UInt32Value',
        syntax => 'proto3',
        _class => 'Google::Protobuf::UInt32Value',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'value',
        json_name => 'value',
        number => 1,
        type => 13,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'value'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'value'} = 1;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'value'} = $value;
    }
    return $self->{'value'};
}

} # end package Google::Protobuf::UInt32Value

{
package Google::Protobuf::BoolValue;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'google.protobuf.BoolValue',
        syntax => 'proto3',
        _class => 'Google::Protobuf::BoolValue',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'value',
        json_name => 'value',
        number => 1,
        type => 8,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'value'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'value'} = 1;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'value'} = $value;
    }
    return $self->{'value'};
}

} # end package Google::Protobuf::BoolValue

{
package Google::Protobuf::StringValue;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'google.protobuf.StringValue',
        syntax => 'proto3',
        _class => 'Google::Protobuf::StringValue',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'value',
        json_name => 'value',
        number => 1,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'value'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'value'} = 1;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'value'} = $value;
    }
    return $self->{'value'};
}

} # end package Google::Protobuf::StringValue

{
package Google::Protobuf::BytesValue;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'google.protobuf.BytesValue',
        syntax => 'proto3',
        _class => 'Google::Protobuf::BytesValue',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'value',
        json_name => 'value',
        number => 1,
        type => 12,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'value'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'value'} = 1;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'value'} = $value;
    }
    return $self->{'value'};
}

} # end package Google::Protobuf::BytesValue

1;
