# Generated by protoc-gen-perl. DO NOT EDIT.
# Source: gnmi_ext.proto

use Google::Protobuf::Duration;

{
package Gnmi_ext::ExtensionID;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Enum';

use constant {
    EID_UNSET => 0,
    EID_EXPERIMENTAL => 999,
};

my %VALUES = (
    'EID_UNSET' => 0,
    'EID_EXPERIMENTAL' => 999,
);

my %NAMES = reverse %VALUES;

sub _values { \%VALUES }
sub name_for { my ($class, $num) = @_; return $NAMES{$num} }
sub value_for { my ($class, $name) = @_; return $VALUES{$name} }

} # end package Gnmi_ext::ExtensionID

{
package Gnmi_ext::Extension;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi_ext.Extension',
        syntax => 'proto3',
        _class => 'Gnmi_ext::Extension',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    push @{$DESCRIPTOR->{oneofs}}, { name => 'ext', fields => [] };
    $DESCRIPTOR->{fields}{1} = {
        name => 'registered_ext',
        json_name => 'registeredExt',
        number => 1,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Gnmi_ext::RegisteredExtension',
    };
    $DESCRIPTOR->{fields_by_name}{'registered_ext'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'registeredExt'} = 1;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'master_arbitration',
        json_name => 'masterArbitration',
        number => 2,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Gnmi_ext::MasterArbitration',
    };
    $DESCRIPTOR->{fields_by_name}{'master_arbitration'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'masterArbitration'} = 2;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 2;
    $DESCRIPTOR->{fields}{3} = {
        name => 'history',
        json_name => 'history',
        number => 3,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Gnmi_ext::History',
    };
    $DESCRIPTOR->{fields_by_name}{'history'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'history'} = 3;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 3;
    $DESCRIPTOR->{fields}{4} = {
        name => 'commit',
        json_name => 'commit',
        number => 4,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Gnmi_ext::Commit',
    };
    $DESCRIPTOR->{fields_by_name}{'commit'} = 4;
    $DESCRIPTOR->{fields_by_json_name}{'commit'} = 4;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 4;
    $DESCRIPTOR->{fields}{5} = {
        name => 'depth',
        json_name => 'depth',
        number => 5,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Gnmi_ext::Depth',
    };
    $DESCRIPTOR->{fields_by_name}{'depth'} = 5;
    $DESCRIPTOR->{fields_by_json_name}{'depth'} = 5;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 5;
    $DESCRIPTOR->{fields}{6} = {
        name => 'config_subscription',
        json_name => 'configSubscription',
        number => 6,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Gnmi_ext::ConfigSubscription',
    };
    $DESCRIPTOR->{fields_by_name}{'config_subscription'} = 6;
    $DESCRIPTOR->{fields_by_json_name}{'configSubscription'} = 6;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 6;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{1}{message_descriptor} = Gnmi_ext::RegisteredExtension->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{2}{message_descriptor} = Gnmi_ext::MasterArbitration->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{3}{message_descriptor} = Gnmi_ext::History->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{4}{message_descriptor} = Gnmi_ext::Commit->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{5}{message_descriptor} = Gnmi_ext::Depth->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{6}{message_descriptor} = Gnmi_ext::ConfigSubscription->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub registered_ext {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 1;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 1;
        $self->{'registered_ext'} = $value;
    }
    return $self->{'registered_ext'};
}

sub master_arbitration {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 2;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 2;
        $self->{'master_arbitration'} = $value;
    }
    return $self->{'master_arbitration'};
}

sub history {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 3;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 3;
        $self->{'history'} = $value;
    }
    return $self->{'history'};
}

sub commit {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 4;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 4;
        $self->{'commit'} = $value;
    }
    return $self->{'commit'};
}

sub depth {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 5;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 5;
        $self->{'depth'} = $value;
    }
    return $self->{'depth'};
}

sub config_subscription {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 6;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 6;
        $self->{'config_subscription'} = $value;
    }
    return $self->{'config_subscription'};
}

} # end package Gnmi_ext::Extension

{
package Gnmi_ext::RegisteredExtension;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi_ext.RegisteredExtension',
        syntax => 'proto3',
        _class => 'Gnmi_ext::RegisteredExtension',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'id',
        json_name => 'id',
        number => 1,
        type => 14,
        label => 1,
        packed => 0,
        oneof_index => undef,
        enum_class => 'Gnmi_ext::ExtensionID',
    };
    $DESCRIPTOR->{fields_by_name}{'id'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'id'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'msg',
        json_name => 'msg',
        number => 2,
        type => 12,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'msg'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'msg'} = 2;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub id {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'id'} = $value;
    }
    return $self->{'id'};
}

sub msg {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'msg'} = $value;
    }
    return $self->{'msg'};
}

} # end package Gnmi_ext::RegisteredExtension

{
package Gnmi_ext::MasterArbitration;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi_ext.MasterArbitration',
        syntax => 'proto3',
        _class => 'Gnmi_ext::MasterArbitration',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'role',
        json_name => 'role',
        number => 1,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi_ext::Role',
    };
    $DESCRIPTOR->{fields_by_name}{'role'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'role'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'election_id',
        json_name => 'electionId',
        number => 2,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi_ext::Uint128',
    };
    $DESCRIPTOR->{fields_by_name}{'election_id'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'electionId'} = 2;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{1}{message_descriptor} = Gnmi_ext::Role->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{2}{message_descriptor} = Gnmi_ext::Uint128->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub role {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'role'} = $value;
    }
    return $self->{'role'};
}

sub election_id {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'election_id'} = $value;
    }
    return $self->{'election_id'};
}

} # end package Gnmi_ext::MasterArbitration

{
package Gnmi_ext::Uint128;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi_ext.Uint128',
        syntax => 'proto3',
        _class => 'Gnmi_ext::Uint128',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'high',
        json_name => 'high',
        number => 1,
        type => 4,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'high'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'high'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'low',
        json_name => 'low',
        number => 2,
        type => 4,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'low'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'low'} = 2;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub high {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'high'} = $value;
    }
    return $self->{'high'};
}

sub low {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'low'} = $value;
    }
    return $self->{'low'};
}

} # end package Gnmi_ext::Uint128

{
package Gnmi_ext::Role;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi_ext.Role',
        syntax => 'proto3',
        _class => 'Gnmi_ext::Role',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'id',
        json_name => 'id',
        number => 1,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'id'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'id'} = 1;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub id {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'id'} = $value;
    }
    return $self->{'id'};
}

} # end package Gnmi_ext::Role

{
package Gnmi_ext::History;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi_ext.History',
        syntax => 'proto3',
        _class => 'Gnmi_ext::History',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    push @{$DESCRIPTOR->{oneofs}}, { name => 'request', fields => [] };
    $DESCRIPTOR->{fields}{1} = {
        name => 'snapshot_time',
        json_name => 'snapshotTime',
        number => 1,
        type => 3,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'snapshot_time'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'snapshotTime'} = 1;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'range',
        json_name => 'range',
        number => 2,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Gnmi_ext::TimeRange',
    };
    $DESCRIPTOR->{fields_by_name}{'range'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'range'} = 2;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 2;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{2}{message_descriptor} = Gnmi_ext::TimeRange->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub snapshot_time {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 1;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 1;
        $self->{'snapshot_time'} = $value;
    }
    return $self->{'snapshot_time'};
}

sub range {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 2;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 2;
        $self->{'range'} = $value;
    }
    return $self->{'range'};
}

} # end package Gnmi_ext::History

{
package Gnmi_ext::TimeRange;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi_ext.TimeRange',
        syntax => 'proto3',
        _class => 'Gnmi_ext::TimeRange',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'start',
        json_name => 'start',
        number => 1,
        type => 3,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'start'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'start'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'end',
        json_name => 'end',
        number => 2,
        type => 3,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'end'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'end'} = 2;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub start {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'start'} = $value;
    }
    return $self->{'start'};
}

sub end {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'end'} = $value;
    }
    return $self->{'end'};
}

} # end package Gnmi_ext::TimeRange

{
package Gnmi_ext::Commit;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi_ext.Commit',
        syntax => 'proto3',
        _class => 'Gnmi_ext::Commit',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    push @{$DESCRIPTOR->{oneofs}}, { name => 'action', fields => [] };
    $DESCRIPTOR->{fields}{1} = {
        name => 'id',
        json_name => 'id',
        number => 1,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'id'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'id'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'commit',
        json_name => 'commit',
        number => 2,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Gnmi_ext::CommitRequest',
    };
    $DESCRIPTOR->{fields_by_name}{'commit'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'commit'} = 2;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 2;
    $DESCRIPTOR->{fields}{3} = {
        name => 'confirm',
        json_name => 'confirm',
        number => 3,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Gnmi_ext::CommitConfirm',
    };
    $DESCRIPTOR->{fields_by_name}{'confirm'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'confirm'} = 3;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 3;
    $DESCRIPTOR->{fields}{4} = {
        name => 'cancel',
        json_name => 'cancel',
        number => 4,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Gnmi_ext::CommitCancel',
    };
    $DESCRIPTOR->{fields_by_name}{'cancel'} = 4;
    $DESCRIPTOR->{fields_by_json_name}{'cancel'} = 4;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 4;
    $DESCRIPTOR->{fields}{5} = {
        name => 'set_rollback_duration',
        json_name => 'setRollbackDuration',
        number => 5,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Gnmi_ext::CommitSetRollbackDuration',
    };
    $DESCRIPTOR->{fields_by_name}{'set_rollback_duration'} = 5;
    $DESCRIPTOR->{fields_by_json_name}{'setRollbackDuration'} = 5;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 5;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{2}{message_descriptor} = Gnmi_ext::CommitRequest->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{3}{message_descriptor} = Gnmi_ext::CommitConfirm->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{4}{message_descriptor} = Gnmi_ext::CommitCancel->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{5}{message_descriptor} = Gnmi_ext::CommitSetRollbackDuration->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub id {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'id'} = $value;
    }
    return $self->{'id'};
}

sub commit {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 2;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 2;
        $self->{'commit'} = $value;
    }
    return $self->{'commit'};
}

sub confirm {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 3;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 3;
        $self->{'confirm'} = $value;
    }
    return $self->{'confirm'};
}

sub cancel {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 4;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 4;
        $self->{'cancel'} = $value;
    }
    return $self->{'cancel'};
}

sub set_rollback_duration {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 5;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 5;
        $self->{'set_rollback_duration'} = $value;
    }
    return $self->{'set_rollback_duration'};
}

} # end package Gnmi_ext::Commit

{
package Gnmi_ext::CommitRequest;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi_ext.CommitRequest',
        syntax => 'proto3',
        _class => 'Gnmi_ext::CommitRequest',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'rollback_duration',
        json_name => 'rollbackDuration',
        number => 1,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Google::Protobuf::Duration',
    };
    $DESCRIPTOR->{fields_by_name}{'rollback_duration'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'rollbackDuration'} = 1;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{1}{message_descriptor} = Google::Protobuf::Duration->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub rollback_duration {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'rollback_duration'} = $value;
    }
    return $self->{'rollback_duration'};
}

} # end package Gnmi_ext::CommitRequest

{
package Gnmi_ext::CommitConfirm;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi_ext.CommitConfirm',
        syntax => 'proto3',
        _class => 'Gnmi_ext::CommitConfirm',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };


    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

} # end package Gnmi_ext::CommitConfirm

{
package Gnmi_ext::CommitCancel;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi_ext.CommitCancel',
        syntax => 'proto3',
        _class => 'Gnmi_ext::CommitCancel',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };


    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

} # end package Gnmi_ext::CommitCancel

{
package Gnmi_ext::CommitSetRollbackDuration;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi_ext.CommitSetRollbackDuration',
        syntax => 'proto3',
        _class => 'Gnmi_ext::CommitSetRollbackDuration',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'rollback_duration',
        json_name => 'rollbackDuration',
        number => 1,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Google::Protobuf::Duration',
    };
    $DESCRIPTOR->{fields_by_name}{'rollback_duration'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'rollbackDuration'} = 1;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{1}{message_descriptor} = Google::Protobuf::Duration->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub rollback_duration {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'rollback_duration'} = $value;
    }
    return $self->{'rollback_duration'};
}

} # end package Gnmi_ext::CommitSetRollbackDuration

{
package Gnmi_ext::Depth;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi_ext.Depth',
        syntax => 'proto3',
        _class => 'Gnmi_ext::Depth',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'level',
        json_name => 'level',
        number => 1,
        type => 13,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'level'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'level'} = 1;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub level {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'level'} = $value;
    }
    return $self->{'level'};
}

} # end package Gnmi_ext::Depth

{
package Gnmi_ext::ConfigSubscription;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi_ext.ConfigSubscription',
        syntax => 'proto3',
        _class => 'Gnmi_ext::ConfigSubscription',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    push @{$DESCRIPTOR->{oneofs}}, { name => 'action', fields => [] };
    $DESCRIPTOR->{fields}{1} = {
        name => 'start',
        json_name => 'start',
        number => 1,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Gnmi_ext::ConfigSubscriptionStart',
    };
    $DESCRIPTOR->{fields_by_name}{'start'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'start'} = 1;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'sync_done',
        json_name => 'syncDone',
        number => 2,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Gnmi_ext::ConfigSubscriptionSyncDone',
    };
    $DESCRIPTOR->{fields_by_name}{'sync_done'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'syncDone'} = 2;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 2;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{1}{message_descriptor} = Gnmi_ext::ConfigSubscriptionStart->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{2}{message_descriptor} = Gnmi_ext::ConfigSubscriptionSyncDone->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub start {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 1;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 1;
        $self->{'start'} = $value;
    }
    return $self->{'start'};
}

sub sync_done {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 2;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 2;
        $self->{'sync_done'} = $value;
    }
    return $self->{'sync_done'};
}

} # end package Gnmi_ext::ConfigSubscription

{
package Gnmi_ext::ConfigSubscriptionStart;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi_ext.ConfigSubscriptionStart',
        syntax => 'proto3',
        _class => 'Gnmi_ext::ConfigSubscriptionStart',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };


    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

} # end package Gnmi_ext::ConfigSubscriptionStart

{
package Gnmi_ext::ConfigSubscriptionSyncDone;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi_ext.ConfigSubscriptionSyncDone',
        syntax => 'proto3',
        _class => 'Gnmi_ext::ConfigSubscriptionSyncDone',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'commit_confirm_id',
        json_name => 'commitConfirmId',
        number => 1,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'commit_confirm_id'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'commitConfirmId'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'server_commit_id',
        json_name => 'serverCommitId',
        number => 2,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'server_commit_id'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'serverCommitId'} = 2;
    $DESCRIPTOR->{fields}{3} = {
        name => 'done',
        json_name => 'done',
        number => 3,
        type => 8,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'done'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'done'} = 3;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub commit_confirm_id {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'commit_confirm_id'} = $value;
    }
    return $self->{'commit_confirm_id'};
}

sub server_commit_id {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'server_commit_id'} = $value;
    }
    return $self->{'server_commit_id'};
}

sub done {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'done'} = $value;
    }
    return $self->{'done'};
}

} # end package Gnmi_ext::ConfigSubscriptionSyncDone

1;
