# Generated by protoc-gen-perl. DO NOT EDIT.
# Source: gnmi.proto

use Gnmi_ext;
use Google::Protobuf::Any;

{
package Gnmi::Encoding;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Enum';

use constant {
    JSON => 0,
    BYTES => 1,
    PROTO => 2,
    ASCII => 3,
    JSON_IETF => 4,
};

my %VALUES = (
    'JSON' => 0,
    'BYTES' => 1,
    'PROTO' => 2,
    'ASCII' => 3,
    'JSON_IETF' => 4,
);

my %NAMES = reverse %VALUES;

sub _values { \%VALUES }
sub name_for { my ($class, $num) = @_; return $NAMES{$num} }
sub value_for { my ($class, $name) = @_; return $VALUES{$name} }

} # end package Gnmi::Encoding

{
package Gnmi::SubscriptionMode;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Enum';

use constant {
    TARGET_DEFINED => 0,
    ON_CHANGE => 1,
    SAMPLE => 2,
};

my %VALUES = (
    'TARGET_DEFINED' => 0,
    'ON_CHANGE' => 1,
    'SAMPLE' => 2,
);

my %NAMES = reverse %VALUES;

sub _values { \%VALUES }
sub name_for { my ($class, $num) = @_; return $NAMES{$num} }
sub value_for { my ($class, $name) = @_; return $VALUES{$name} }

} # end package Gnmi::SubscriptionMode

{
package Gnmi::Notification;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.Notification',
        syntax => 'proto3',
        _class => 'Gnmi::Notification',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'timestamp',
        json_name => 'timestamp',
        number => 1,
        type => 3,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'timestamp'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'timestamp'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'prefix',
        json_name => 'prefix',
        number => 2,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Path',
    };
    $DESCRIPTOR->{fields_by_name}{'prefix'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'prefix'} = 2;
    $DESCRIPTOR->{fields}{4} = {
        name => 'update',
        json_name => 'update',
        number => 4,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Update',
    };
    $DESCRIPTOR->{fields_by_name}{'update'} = 4;
    $DESCRIPTOR->{fields_by_json_name}{'update'} = 4;
    $DESCRIPTOR->{fields}{5} = {
        name => 'delete',
        json_name => 'delete',
        number => 5,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Path',
    };
    $DESCRIPTOR->{fields_by_name}{'delete'} = 5;
    $DESCRIPTOR->{fields_by_json_name}{'delete'} = 5;
    $DESCRIPTOR->{fields}{6} = {
        name => 'atomic',
        json_name => 'atomic',
        number => 6,
        type => 8,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'atomic'} = 6;
    $DESCRIPTOR->{fields_by_json_name}{'atomic'} = 6;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{2}{message_descriptor} = Gnmi::Path->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{4}{message_descriptor} = Gnmi::Update->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{5}{message_descriptor} = Gnmi::Path->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub timestamp {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'timestamp'} = $value;
    }
    return $self->{'timestamp'};
}

sub prefix {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'prefix'} = $value;
    }
    return $self->{'prefix'};
}

sub update {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'update'} = $value;
    }
    return $self->{'update'};
}

sub delete {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'delete'} = $value;
    }
    return $self->{'delete'};
}

sub atomic {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'atomic'} = $value;
    }
    return $self->{'atomic'};
}

} # end package Gnmi::Notification

{
package Gnmi::Update;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.Update',
        syntax => 'proto3',
        _class => 'Gnmi::Update',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'path',
        json_name => 'path',
        number => 1,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Path',
    };
    $DESCRIPTOR->{fields_by_name}{'path'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'path'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'value',
        json_name => 'value',
        number => 2,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Value',
    };
    $DESCRIPTOR->{fields_by_name}{'value'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'value'} = 2;
    $DESCRIPTOR->{fields}{3} = {
        name => 'val',
        json_name => 'val',
        number => 3,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::TypedValue',
    };
    $DESCRIPTOR->{fields_by_name}{'val'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'val'} = 3;
    $DESCRIPTOR->{fields}{4} = {
        name => 'duplicates',
        json_name => 'duplicates',
        number => 4,
        type => 13,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'duplicates'} = 4;
    $DESCRIPTOR->{fields_by_json_name}{'duplicates'} = 4;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{1}{message_descriptor} = Gnmi::Path->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{2}{message_descriptor} = Gnmi::Value->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{3}{message_descriptor} = Gnmi::TypedValue->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub path {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'path'} = $value;
    }
    return $self->{'path'};
}

sub value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'value'} = $value;
    }
    return $self->{'value'};
}

sub val {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'val'} = $value;
    }
    return $self->{'val'};
}

sub duplicates {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'duplicates'} = $value;
    }
    return $self->{'duplicates'};
}

} # end package Gnmi::Update

{
package Gnmi::TypedValue;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.TypedValue',
        syntax => 'proto3',
        _class => 'Gnmi::TypedValue',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    push @{$DESCRIPTOR->{oneofs}}, { name => 'value', fields => [] };
    $DESCRIPTOR->{fields}{1} = {
        name => 'string_val',
        json_name => 'stringVal',
        number => 1,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'string_val'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'stringVal'} = 1;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'int_val',
        json_name => 'intVal',
        number => 2,
        type => 3,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'int_val'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'intVal'} = 2;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 2;
    $DESCRIPTOR->{fields}{3} = {
        name => 'uint_val',
        json_name => 'uintVal',
        number => 3,
        type => 4,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'uint_val'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'uintVal'} = 3;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 3;
    $DESCRIPTOR->{fields}{4} = {
        name => 'bool_val',
        json_name => 'boolVal',
        number => 4,
        type => 8,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'bool_val'} = 4;
    $DESCRIPTOR->{fields_by_json_name}{'boolVal'} = 4;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 4;
    $DESCRIPTOR->{fields}{5} = {
        name => 'bytes_val',
        json_name => 'bytesVal',
        number => 5,
        type => 12,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'bytes_val'} = 5;
    $DESCRIPTOR->{fields_by_json_name}{'bytesVal'} = 5;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 5;
    $DESCRIPTOR->{fields}{6} = {
        name => 'float_val',
        json_name => 'floatVal',
        number => 6,
        type => 2,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'float_val'} = 6;
    $DESCRIPTOR->{fields_by_json_name}{'floatVal'} = 6;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 6;
    $DESCRIPTOR->{fields}{14} = {
        name => 'double_val',
        json_name => 'doubleVal',
        number => 14,
        type => 1,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'double_val'} = 14;
    $DESCRIPTOR->{fields_by_json_name}{'doubleVal'} = 14;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 14;
    $DESCRIPTOR->{fields}{7} = {
        name => 'decimal_val',
        json_name => 'decimalVal',
        number => 7,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Gnmi::Decimal64',
    };
    $DESCRIPTOR->{fields_by_name}{'decimal_val'} = 7;
    $DESCRIPTOR->{fields_by_json_name}{'decimalVal'} = 7;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 7;
    $DESCRIPTOR->{fields}{8} = {
        name => 'leaflist_val',
        json_name => 'leaflistVal',
        number => 8,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Gnmi::ScalarArray',
    };
    $DESCRIPTOR->{fields_by_name}{'leaflist_val'} = 8;
    $DESCRIPTOR->{fields_by_json_name}{'leaflistVal'} = 8;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 8;
    $DESCRIPTOR->{fields}{9} = {
        name => 'any_val',
        json_name => 'anyVal',
        number => 9,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Google::Protobuf::Any',
    };
    $DESCRIPTOR->{fields_by_name}{'any_val'} = 9;
    $DESCRIPTOR->{fields_by_json_name}{'anyVal'} = 9;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 9;
    $DESCRIPTOR->{fields}{10} = {
        name => 'json_val',
        json_name => 'jsonVal',
        number => 10,
        type => 12,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'json_val'} = 10;
    $DESCRIPTOR->{fields_by_json_name}{'jsonVal'} = 10;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 10;
    $DESCRIPTOR->{fields}{11} = {
        name => 'json_ietf_val',
        json_name => 'jsonIetfVal',
        number => 11,
        type => 12,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'json_ietf_val'} = 11;
    $DESCRIPTOR->{fields_by_json_name}{'jsonIetfVal'} = 11;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 11;
    $DESCRIPTOR->{fields}{12} = {
        name => 'ascii_val',
        json_name => 'asciiVal',
        number => 12,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'ascii_val'} = 12;
    $DESCRIPTOR->{fields_by_json_name}{'asciiVal'} = 12;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 12;
    $DESCRIPTOR->{fields}{13} = {
        name => 'proto_bytes',
        json_name => 'protoBytes',
        number => 13,
        type => 12,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'proto_bytes'} = 13;
    $DESCRIPTOR->{fields_by_json_name}{'protoBytes'} = 13;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 13;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{7}{message_descriptor} = Gnmi::Decimal64->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{8}{message_descriptor} = Gnmi::ScalarArray->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{9}{message_descriptor} = Google::Protobuf::Any->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub string_val {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 1;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 1;
        $self->{'string_val'} = $value;
    }
    return $self->{'string_val'};
}

sub int_val {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 2;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 2;
        $self->{'int_val'} = $value;
    }
    return $self->{'int_val'};
}

sub uint_val {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 3;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 3;
        $self->{'uint_val'} = $value;
    }
    return $self->{'uint_val'};
}

sub bool_val {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 4;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 4;
        $self->{'bool_val'} = $value;
    }
    return $self->{'bool_val'};
}

sub bytes_val {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 5;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 5;
        $self->{'bytes_val'} = $value;
    }
    return $self->{'bytes_val'};
}

sub float_val {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 6;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 6;
        $self->{'float_val'} = $value;
    }
    return $self->{'float_val'};
}

sub double_val {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 14;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 14;
        $self->{'double_val'} = $value;
    }
    return $self->{'double_val'};
}

sub decimal_val {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 7;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 7;
        $self->{'decimal_val'} = $value;
    }
    return $self->{'decimal_val'};
}

sub leaflist_val {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 8;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 8;
        $self->{'leaflist_val'} = $value;
    }
    return $self->{'leaflist_val'};
}

sub any_val {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 9;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 9;
        $self->{'any_val'} = $value;
    }
    return $self->{'any_val'};
}

sub json_val {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 10;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 10;
        $self->{'json_val'} = $value;
    }
    return $self->{'json_val'};
}

sub json_ietf_val {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 11;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 11;
        $self->{'json_ietf_val'} = $value;
    }
    return $self->{'json_ietf_val'};
}

sub ascii_val {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 12;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 12;
        $self->{'ascii_val'} = $value;
    }
    return $self->{'ascii_val'};
}

sub proto_bytes {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 13;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 13;
        $self->{'proto_bytes'} = $value;
    }
    return $self->{'proto_bytes'};
}

} # end package Gnmi::TypedValue

{
package Gnmi::Path;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.Path',
        syntax => 'proto3',
        _class => 'Gnmi::Path',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'element',
        json_name => 'element',
        number => 1,
        type => 9,
        label => 3,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'element'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'element'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'origin',
        json_name => 'origin',
        number => 2,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'origin'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'origin'} = 2;
    $DESCRIPTOR->{fields}{3} = {
        name => 'elem',
        json_name => 'elem',
        number => 3,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::PathElem',
    };
    $DESCRIPTOR->{fields_by_name}{'elem'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'elem'} = 3;
    $DESCRIPTOR->{fields}{4} = {
        name => 'target',
        json_name => 'target',
        number => 4,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'target'} = 4;
    $DESCRIPTOR->{fields_by_json_name}{'target'} = 4;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{3}{message_descriptor} = Gnmi::PathElem->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub element {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'element'} = $value;
    }
    return $self->{'element'};
}

sub origin {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'origin'} = $value;
    }
    return $self->{'origin'};
}

sub elem {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'elem'} = $value;
    }
    return $self->{'elem'};
}

sub target {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'target'} = $value;
    }
    return $self->{'target'};
}

} # end package Gnmi::Path

{
package Gnmi::PathElem::KeyEntry;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.PathElem.KeyEntry',
        syntax => 'proto3',
        _class => 'Gnmi::PathElem::KeyEntry',
        is_map_entry => 1,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'key',
        json_name => 'key',
        number => 1,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'key'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'key'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'value',
        json_name => 'value',
        number => 2,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'value'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'value'} = 2;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub key {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'key'} = $value;
    }
    return $self->{'key'};
}

sub value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'value'} = $value;
    }
    return $self->{'value'};
}

} # end package Gnmi::PathElem::KeyEntry

{
package Gnmi::PathElem;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.PathElem',
        syntax => 'proto3',
        _class => 'Gnmi::PathElem',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'name',
        json_name => 'name',
        number => 1,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'name'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'name'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'key',
        json_name => 'key',
        number => 2,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::PathElem::KeyEntry',
        map_entry => {
            key_type => 9,
            value_type => 9,
        },
    };
    $DESCRIPTOR->{fields_by_name}{'key'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'key'} = 2;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{2}{message_descriptor} = Gnmi::PathElem::KeyEntry->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub name {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'name'} = $value;
    }
    return $self->{'name'};
}

sub key {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'key'} = $value;
    }
    return $self->{'key'};
}

} # end package Gnmi::PathElem

{
package Gnmi::Value;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.Value',
        syntax => 'proto3',
        _class => 'Gnmi::Value',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'value',
        json_name => 'value',
        number => 1,
        type => 12,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'value'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'value'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'type',
        json_name => 'type',
        number => 2,
        type => 14,
        label => 1,
        packed => 0,
        oneof_index => undef,
        enum_class => 'Gnmi::Encoding',
    };
    $DESCRIPTOR->{fields_by_name}{'type'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'type'} = 2;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'value'} = $value;
    }
    return $self->{'value'};
}

sub type {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'type'} = $value;
    }
    return $self->{'type'};
}

} # end package Gnmi::Value

{
package Gnmi::Error;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.Error',
        syntax => 'proto3',
        _class => 'Gnmi::Error',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'code',
        json_name => 'code',
        number => 1,
        type => 13,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'code'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'code'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'message',
        json_name => 'message',
        number => 2,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'message'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'message'} = 2;
    $DESCRIPTOR->{fields}{3} = {
        name => 'data',
        json_name => 'data',
        number => 3,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Google::Protobuf::Any',
    };
    $DESCRIPTOR->{fields_by_name}{'data'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'data'} = 3;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{3}{message_descriptor} = Google::Protobuf::Any->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub code {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'code'} = $value;
    }
    return $self->{'code'};
}

sub message {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'message'} = $value;
    }
    return $self->{'message'};
}

sub data {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'data'} = $value;
    }
    return $self->{'data'};
}

} # end package Gnmi::Error

{
package Gnmi::Decimal64;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.Decimal64',
        syntax => 'proto3',
        _class => 'Gnmi::Decimal64',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'digits',
        json_name => 'digits',
        number => 1,
        type => 3,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'digits'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'digits'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'precision',
        json_name => 'precision',
        number => 2,
        type => 13,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'precision'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'precision'} = 2;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub digits {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'digits'} = $value;
    }
    return $self->{'digits'};
}

sub precision {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'precision'} = $value;
    }
    return $self->{'precision'};
}

} # end package Gnmi::Decimal64

{
package Gnmi::ScalarArray;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.ScalarArray',
        syntax => 'proto3',
        _class => 'Gnmi::ScalarArray',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'element',
        json_name => 'element',
        number => 1,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::TypedValue',
    };
    $DESCRIPTOR->{fields_by_name}{'element'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'element'} = 1;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{1}{message_descriptor} = Gnmi::TypedValue->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub element {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'element'} = $value;
    }
    return $self->{'element'};
}

} # end package Gnmi::ScalarArray

{
package Gnmi::SubscribeRequest;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.SubscribeRequest',
        syntax => 'proto3',
        _class => 'Gnmi::SubscribeRequest',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    push @{$DESCRIPTOR->{oneofs}}, { name => 'request', fields => [] };
    $DESCRIPTOR->{fields}{1} = {
        name => 'subscribe',
        json_name => 'subscribe',
        number => 1,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Gnmi::SubscriptionList',
    };
    $DESCRIPTOR->{fields_by_name}{'subscribe'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'subscribe'} = 1;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 1;
    $DESCRIPTOR->{fields}{3} = {
        name => 'poll',
        json_name => 'poll',
        number => 3,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Gnmi::Poll',
    };
    $DESCRIPTOR->{fields_by_name}{'poll'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'poll'} = 3;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 3;
    $DESCRIPTOR->{fields}{5} = {
        name => 'extension',
        json_name => 'extension',
        number => 5,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi_ext::Extension',
    };
    $DESCRIPTOR->{fields_by_name}{'extension'} = 5;
    $DESCRIPTOR->{fields_by_json_name}{'extension'} = 5;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{1}{message_descriptor} = Gnmi::SubscriptionList->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{3}{message_descriptor} = Gnmi::Poll->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{5}{message_descriptor} = Gnmi_ext::Extension->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub subscribe {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 1;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 1;
        $self->{'subscribe'} = $value;
    }
    return $self->{'subscribe'};
}

sub poll {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 3;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 3;
        $self->{'poll'} = $value;
    }
    return $self->{'poll'};
}

sub extension {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'extension'} = $value;
    }
    return $self->{'extension'};
}

} # end package Gnmi::SubscribeRequest

{
package Gnmi::Poll;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.Poll',
        syntax => 'proto3',
        _class => 'Gnmi::Poll',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };


    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

} # end package Gnmi::Poll

{
package Gnmi::SubscribeResponse;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.SubscribeResponse',
        syntax => 'proto3',
        _class => 'Gnmi::SubscribeResponse',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    push @{$DESCRIPTOR->{oneofs}}, { name => 'response', fields => [] };
    $DESCRIPTOR->{fields}{1} = {
        name => 'update',
        json_name => 'update',
        number => 1,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Gnmi::Notification',
    };
    $DESCRIPTOR->{fields_by_name}{'update'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'update'} = 1;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 1;
    $DESCRIPTOR->{fields}{3} = {
        name => 'sync_response',
        json_name => 'syncResponse',
        number => 3,
        type => 8,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'sync_response'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'syncResponse'} = 3;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 3;
    $DESCRIPTOR->{fields}{4} = {
        name => 'error',
        json_name => 'error',
        number => 4,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => 0,
        message_class => 'Gnmi::Error',
    };
    $DESCRIPTOR->{fields_by_name}{'error'} = 4;
    $DESCRIPTOR->{fields_by_json_name}{'error'} = 4;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 4;
    $DESCRIPTOR->{fields}{5} = {
        name => 'extension',
        json_name => 'extension',
        number => 5,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi_ext::Extension',
    };
    $DESCRIPTOR->{fields_by_name}{'extension'} = 5;
    $DESCRIPTOR->{fields_by_json_name}{'extension'} = 5;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{1}{message_descriptor} = Gnmi::Notification->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{4}{message_descriptor} = Gnmi::Error->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{5}{message_descriptor} = Gnmi_ext::Extension->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub update {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 1;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 1;
        $self->{'update'} = $value;
    }
    return $self->{'update'};
}

sub sync_response {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 3;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 3;
        $self->{'sync_response'} = $value;
    }
    return $self->{'sync_response'};
}

sub error {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 4;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 4;
        $self->{'error'} = $value;
    }
    return $self->{'error'};
}

sub extension {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'extension'} = $value;
    }
    return $self->{'extension'};
}

} # end package Gnmi::SubscribeResponse

{
package Gnmi::SubscriptionList::Mode;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Enum';

use constant {
    STREAM => 0,
    ONCE => 1,
    POLL => 2,
};

my %VALUES = (
    'STREAM' => 0,
    'ONCE' => 1,
    'POLL' => 2,
);

my %NAMES = reverse %VALUES;

sub _values { \%VALUES }
sub name_for { my ($class, $num) = @_; return $NAMES{$num} }
sub value_for { my ($class, $name) = @_; return $VALUES{$name} }

} # end package Gnmi::SubscriptionList::Mode

{
package Gnmi::SubscriptionList;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.SubscriptionList',
        syntax => 'proto3',
        _class => 'Gnmi::SubscriptionList',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'prefix',
        json_name => 'prefix',
        number => 1,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Path',
    };
    $DESCRIPTOR->{fields_by_name}{'prefix'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'prefix'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'subscription',
        json_name => 'subscription',
        number => 2,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Subscription',
    };
    $DESCRIPTOR->{fields_by_name}{'subscription'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'subscription'} = 2;
    $DESCRIPTOR->{fields}{4} = {
        name => 'qos',
        json_name => 'qos',
        number => 4,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::QOSMarking',
    };
    $DESCRIPTOR->{fields_by_name}{'qos'} = 4;
    $DESCRIPTOR->{fields_by_json_name}{'qos'} = 4;
    $DESCRIPTOR->{fields}{5} = {
        name => 'mode',
        json_name => 'mode',
        number => 5,
        type => 14,
        label => 1,
        packed => 0,
        oneof_index => undef,
        enum_class => 'Gnmi::SubscriptionList::Mode',
    };
    $DESCRIPTOR->{fields_by_name}{'mode'} = 5;
    $DESCRIPTOR->{fields_by_json_name}{'mode'} = 5;
    $DESCRIPTOR->{fields}{6} = {
        name => 'allow_aggregation',
        json_name => 'allowAggregation',
        number => 6,
        type => 8,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'allow_aggregation'} = 6;
    $DESCRIPTOR->{fields_by_json_name}{'allowAggregation'} = 6;
    $DESCRIPTOR->{fields}{7} = {
        name => 'use_models',
        json_name => 'useModels',
        number => 7,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::ModelData',
    };
    $DESCRIPTOR->{fields_by_name}{'use_models'} = 7;
    $DESCRIPTOR->{fields_by_json_name}{'useModels'} = 7;
    $DESCRIPTOR->{fields}{8} = {
        name => 'encoding',
        json_name => 'encoding',
        number => 8,
        type => 14,
        label => 1,
        packed => 0,
        oneof_index => undef,
        enum_class => 'Gnmi::Encoding',
    };
    $DESCRIPTOR->{fields_by_name}{'encoding'} = 8;
    $DESCRIPTOR->{fields_by_json_name}{'encoding'} = 8;
    $DESCRIPTOR->{fields}{9} = {
        name => 'updates_only',
        json_name => 'updatesOnly',
        number => 9,
        type => 8,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'updates_only'} = 9;
    $DESCRIPTOR->{fields_by_json_name}{'updatesOnly'} = 9;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{1}{message_descriptor} = Gnmi::Path->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{2}{message_descriptor} = Gnmi::Subscription->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{4}{message_descriptor} = Gnmi::QOSMarking->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{7}{message_descriptor} = Gnmi::ModelData->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub prefix {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'prefix'} = $value;
    }
    return $self->{'prefix'};
}

sub subscription {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'subscription'} = $value;
    }
    return $self->{'subscription'};
}

sub qos {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'qos'} = $value;
    }
    return $self->{'qos'};
}

sub mode {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'mode'} = $value;
    }
    return $self->{'mode'};
}

sub allow_aggregation {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'allow_aggregation'} = $value;
    }
    return $self->{'allow_aggregation'};
}

sub use_models {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'use_models'} = $value;
    }
    return $self->{'use_models'};
}

sub encoding {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'encoding'} = $value;
    }
    return $self->{'encoding'};
}

sub updates_only {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'updates_only'} = $value;
    }
    return $self->{'updates_only'};
}

} # end package Gnmi::SubscriptionList

{
package Gnmi::Subscription;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.Subscription',
        syntax => 'proto3',
        _class => 'Gnmi::Subscription',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'path',
        json_name => 'path',
        number => 1,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Path',
    };
    $DESCRIPTOR->{fields_by_name}{'path'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'path'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'mode',
        json_name => 'mode',
        number => 2,
        type => 14,
        label => 1,
        packed => 0,
        oneof_index => undef,
        enum_class => 'Gnmi::SubscriptionMode',
    };
    $DESCRIPTOR->{fields_by_name}{'mode'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'mode'} = 2;
    $DESCRIPTOR->{fields}{3} = {
        name => 'sample_interval',
        json_name => 'sampleInterval',
        number => 3,
        type => 4,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'sample_interval'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'sampleInterval'} = 3;
    $DESCRIPTOR->{fields}{4} = {
        name => 'suppress_redundant',
        json_name => 'suppressRedundant',
        number => 4,
        type => 8,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'suppress_redundant'} = 4;
    $DESCRIPTOR->{fields_by_json_name}{'suppressRedundant'} = 4;
    $DESCRIPTOR->{fields}{5} = {
        name => 'heartbeat_interval',
        json_name => 'heartbeatInterval',
        number => 5,
        type => 4,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'heartbeat_interval'} = 5;
    $DESCRIPTOR->{fields_by_json_name}{'heartbeatInterval'} = 5;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{1}{message_descriptor} = Gnmi::Path->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub path {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'path'} = $value;
    }
    return $self->{'path'};
}

sub mode {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'mode'} = $value;
    }
    return $self->{'mode'};
}

sub sample_interval {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'sample_interval'} = $value;
    }
    return $self->{'sample_interval'};
}

sub suppress_redundant {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'suppress_redundant'} = $value;
    }
    return $self->{'suppress_redundant'};
}

sub heartbeat_interval {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'heartbeat_interval'} = $value;
    }
    return $self->{'heartbeat_interval'};
}

} # end package Gnmi::Subscription

{
package Gnmi::QOSMarking;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.QOSMarking',
        syntax => 'proto3',
        _class => 'Gnmi::QOSMarking',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'marking',
        json_name => 'marking',
        number => 1,
        type => 13,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'marking'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'marking'} = 1;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub marking {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'marking'} = $value;
    }
    return $self->{'marking'};
}

} # end package Gnmi::QOSMarking

{
package Gnmi::SetRequest;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.SetRequest',
        syntax => 'proto3',
        _class => 'Gnmi::SetRequest',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'prefix',
        json_name => 'prefix',
        number => 1,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Path',
    };
    $DESCRIPTOR->{fields_by_name}{'prefix'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'prefix'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'delete',
        json_name => 'delete',
        number => 2,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Path',
    };
    $DESCRIPTOR->{fields_by_name}{'delete'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'delete'} = 2;
    $DESCRIPTOR->{fields}{3} = {
        name => 'replace',
        json_name => 'replace',
        number => 3,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Update',
    };
    $DESCRIPTOR->{fields_by_name}{'replace'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'replace'} = 3;
    $DESCRIPTOR->{fields}{4} = {
        name => 'update',
        json_name => 'update',
        number => 4,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Update',
    };
    $DESCRIPTOR->{fields_by_name}{'update'} = 4;
    $DESCRIPTOR->{fields_by_json_name}{'update'} = 4;
    $DESCRIPTOR->{fields}{6} = {
        name => 'union_replace',
        json_name => 'unionReplace',
        number => 6,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Update',
    };
    $DESCRIPTOR->{fields_by_name}{'union_replace'} = 6;
    $DESCRIPTOR->{fields_by_json_name}{'unionReplace'} = 6;
    $DESCRIPTOR->{fields}{5} = {
        name => 'extension',
        json_name => 'extension',
        number => 5,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi_ext::Extension',
    };
    $DESCRIPTOR->{fields_by_name}{'extension'} = 5;
    $DESCRIPTOR->{fields_by_json_name}{'extension'} = 5;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{1}{message_descriptor} = Gnmi::Path->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{2}{message_descriptor} = Gnmi::Path->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{3}{message_descriptor} = Gnmi::Update->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{4}{message_descriptor} = Gnmi::Update->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{6}{message_descriptor} = Gnmi::Update->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{5}{message_descriptor} = Gnmi_ext::Extension->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub prefix {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'prefix'} = $value;
    }
    return $self->{'prefix'};
}

sub delete {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'delete'} = $value;
    }
    return $self->{'delete'};
}

sub replace {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'replace'} = $value;
    }
    return $self->{'replace'};
}

sub update {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'update'} = $value;
    }
    return $self->{'update'};
}

sub union_replace {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'union_replace'} = $value;
    }
    return $self->{'union_replace'};
}

sub extension {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'extension'} = $value;
    }
    return $self->{'extension'};
}

} # end package Gnmi::SetRequest

{
package Gnmi::SetResponse;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.SetResponse',
        syntax => 'proto3',
        _class => 'Gnmi::SetResponse',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'prefix',
        json_name => 'prefix',
        number => 1,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Path',
    };
    $DESCRIPTOR->{fields_by_name}{'prefix'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'prefix'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'response',
        json_name => 'response',
        number => 2,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::UpdateResult',
    };
    $DESCRIPTOR->{fields_by_name}{'response'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'response'} = 2;
    $DESCRIPTOR->{fields}{3} = {
        name => 'message',
        json_name => 'message',
        number => 3,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Error',
    };
    $DESCRIPTOR->{fields_by_name}{'message'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'message'} = 3;
    $DESCRIPTOR->{fields}{4} = {
        name => 'timestamp',
        json_name => 'timestamp',
        number => 4,
        type => 3,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'timestamp'} = 4;
    $DESCRIPTOR->{fields_by_json_name}{'timestamp'} = 4;
    $DESCRIPTOR->{fields}{5} = {
        name => 'extension',
        json_name => 'extension',
        number => 5,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi_ext::Extension',
    };
    $DESCRIPTOR->{fields_by_name}{'extension'} = 5;
    $DESCRIPTOR->{fields_by_json_name}{'extension'} = 5;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{1}{message_descriptor} = Gnmi::Path->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{2}{message_descriptor} = Gnmi::UpdateResult->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{3}{message_descriptor} = Gnmi::Error->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{5}{message_descriptor} = Gnmi_ext::Extension->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub prefix {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'prefix'} = $value;
    }
    return $self->{'prefix'};
}

sub response {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'response'} = $value;
    }
    return $self->{'response'};
}

sub message {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'message'} = $value;
    }
    return $self->{'message'};
}

sub timestamp {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'timestamp'} = $value;
    }
    return $self->{'timestamp'};
}

sub extension {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'extension'} = $value;
    }
    return $self->{'extension'};
}

} # end package Gnmi::SetResponse

{
package Gnmi::UpdateResult::Operation;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Enum';

use constant {
    INVALID => 0,
    DELETE => 1,
    REPLACE => 2,
    UPDATE => 3,
    UNION_REPLACE => 4,
};

my %VALUES = (
    'INVALID' => 0,
    'DELETE' => 1,
    'REPLACE' => 2,
    'UPDATE' => 3,
    'UNION_REPLACE' => 4,
);

my %NAMES = reverse %VALUES;

sub _values { \%VALUES }
sub name_for { my ($class, $num) = @_; return $NAMES{$num} }
sub value_for { my ($class, $name) = @_; return $VALUES{$name} }

} # end package Gnmi::UpdateResult::Operation

{
package Gnmi::UpdateResult;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.UpdateResult',
        syntax => 'proto3',
        _class => 'Gnmi::UpdateResult',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'timestamp',
        json_name => 'timestamp',
        number => 1,
        type => 3,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'timestamp'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'timestamp'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'path',
        json_name => 'path',
        number => 2,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Path',
    };
    $DESCRIPTOR->{fields_by_name}{'path'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'path'} = 2;
    $DESCRIPTOR->{fields}{3} = {
        name => 'message',
        json_name => 'message',
        number => 3,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Error',
    };
    $DESCRIPTOR->{fields_by_name}{'message'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'message'} = 3;
    $DESCRIPTOR->{fields}{4} = {
        name => 'op',
        json_name => 'op',
        number => 4,
        type => 14,
        label => 1,
        packed => 0,
        oneof_index => undef,
        enum_class => 'Gnmi::UpdateResult::Operation',
    };
    $DESCRIPTOR->{fields_by_name}{'op'} = 4;
    $DESCRIPTOR->{fields_by_json_name}{'op'} = 4;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{2}{message_descriptor} = Gnmi::Path->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{3}{message_descriptor} = Gnmi::Error->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub timestamp {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'timestamp'} = $value;
    }
    return $self->{'timestamp'};
}

sub path {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'path'} = $value;
    }
    return $self->{'path'};
}

sub message {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'message'} = $value;
    }
    return $self->{'message'};
}

sub op {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'op'} = $value;
    }
    return $self->{'op'};
}

} # end package Gnmi::UpdateResult

{
package Gnmi::GetRequest::DataType;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Enum';

use constant {
    ALL => 0,
    CONFIG => 1,
    STATE => 2,
    OPERATIONAL => 3,
};

my %VALUES = (
    'ALL' => 0,
    'CONFIG' => 1,
    'STATE' => 2,
    'OPERATIONAL' => 3,
);

my %NAMES = reverse %VALUES;

sub _values { \%VALUES }
sub name_for { my ($class, $num) = @_; return $NAMES{$num} }
sub value_for { my ($class, $name) = @_; return $VALUES{$name} }

} # end package Gnmi::GetRequest::DataType

{
package Gnmi::GetRequest;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.GetRequest',
        syntax => 'proto3',
        _class => 'Gnmi::GetRequest',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'prefix',
        json_name => 'prefix',
        number => 1,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Path',
    };
    $DESCRIPTOR->{fields_by_name}{'prefix'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'prefix'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'path',
        json_name => 'path',
        number => 2,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Path',
    };
    $DESCRIPTOR->{fields_by_name}{'path'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'path'} = 2;
    $DESCRIPTOR->{fields}{3} = {
        name => 'type',
        json_name => 'type',
        number => 3,
        type => 14,
        label => 1,
        packed => 0,
        oneof_index => undef,
        enum_class => 'Gnmi::GetRequest::DataType',
    };
    $DESCRIPTOR->{fields_by_name}{'type'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'type'} = 3;
    $DESCRIPTOR->{fields}{5} = {
        name => 'encoding',
        json_name => 'encoding',
        number => 5,
        type => 14,
        label => 1,
        packed => 0,
        oneof_index => undef,
        enum_class => 'Gnmi::Encoding',
    };
    $DESCRIPTOR->{fields_by_name}{'encoding'} = 5;
    $DESCRIPTOR->{fields_by_json_name}{'encoding'} = 5;
    $DESCRIPTOR->{fields}{6} = {
        name => 'use_models',
        json_name => 'useModels',
        number => 6,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::ModelData',
    };
    $DESCRIPTOR->{fields_by_name}{'use_models'} = 6;
    $DESCRIPTOR->{fields_by_json_name}{'useModels'} = 6;
    $DESCRIPTOR->{fields}{7} = {
        name => 'extension',
        json_name => 'extension',
        number => 7,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi_ext::Extension',
    };
    $DESCRIPTOR->{fields_by_name}{'extension'} = 7;
    $DESCRIPTOR->{fields_by_json_name}{'extension'} = 7;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{1}{message_descriptor} = Gnmi::Path->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{2}{message_descriptor} = Gnmi::Path->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{6}{message_descriptor} = Gnmi::ModelData->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{7}{message_descriptor} = Gnmi_ext::Extension->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub prefix {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'prefix'} = $value;
    }
    return $self->{'prefix'};
}

sub path {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'path'} = $value;
    }
    return $self->{'path'};
}

sub type {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'type'} = $value;
    }
    return $self->{'type'};
}

sub encoding {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'encoding'} = $value;
    }
    return $self->{'encoding'};
}

sub use_models {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'use_models'} = $value;
    }
    return $self->{'use_models'};
}

sub extension {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'extension'} = $value;
    }
    return $self->{'extension'};
}

} # end package Gnmi::GetRequest

{
package Gnmi::GetResponse;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.GetResponse',
        syntax => 'proto3',
        _class => 'Gnmi::GetResponse',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'notification',
        json_name => 'notification',
        number => 1,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Notification',
    };
    $DESCRIPTOR->{fields_by_name}{'notification'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'notification'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'error',
        json_name => 'error',
        number => 2,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::Error',
    };
    $DESCRIPTOR->{fields_by_name}{'error'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'error'} = 2;
    $DESCRIPTOR->{fields}{3} = {
        name => 'extension',
        json_name => 'extension',
        number => 3,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi_ext::Extension',
    };
    $DESCRIPTOR->{fields_by_name}{'extension'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'extension'} = 3;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{1}{message_descriptor} = Gnmi::Notification->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{2}{message_descriptor} = Gnmi::Error->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{3}{message_descriptor} = Gnmi_ext::Extension->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub notification {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'notification'} = $value;
    }
    return $self->{'notification'};
}

sub error {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'error'} = $value;
    }
    return $self->{'error'};
}

sub extension {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'extension'} = $value;
    }
    return $self->{'extension'};
}

} # end package Gnmi::GetResponse

{
package Gnmi::CapabilityRequest;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.CapabilityRequest',
        syntax => 'proto3',
        _class => 'Gnmi::CapabilityRequest',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'extension',
        json_name => 'extension',
        number => 1,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi_ext::Extension',
    };
    $DESCRIPTOR->{fields_by_name}{'extension'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'extension'} = 1;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{1}{message_descriptor} = Gnmi_ext::Extension->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub extension {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'extension'} = $value;
    }
    return $self->{'extension'};
}

} # end package Gnmi::CapabilityRequest

{
package Gnmi::CapabilityResponse;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.CapabilityResponse',
        syntax => 'proto3',
        _class => 'Gnmi::CapabilityResponse',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'supported_models',
        json_name => 'supportedModels',
        number => 1,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi::ModelData',
    };
    $DESCRIPTOR->{fields_by_name}{'supported_models'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'supportedModels'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'supported_encodings',
        json_name => 'supportedEncodings',
        number => 2,
        type => 14,
        label => 3,
        packed => 1,
        oneof_index => undef,
        enum_class => 'Gnmi::Encoding',
    };
    $DESCRIPTOR->{fields_by_name}{'supported_encodings'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'supportedEncodings'} = 2;
    $DESCRIPTOR->{fields}{3} = {
        name => 'gNMI_version',
        json_name => 'gNMIVersion',
        number => 3,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'gNMI_version'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'gNMIVersion'} = 3;
    $DESCRIPTOR->{fields}{4} = {
        name => 'extension',
        json_name => 'extension',
        number => 4,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Gnmi_ext::Extension',
    };
    $DESCRIPTOR->{fields_by_name}{'extension'} = 4;
    $DESCRIPTOR->{fields_by_json_name}{'extension'} = 4;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{1}{message_descriptor} = Gnmi::ModelData->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{4}{message_descriptor} = Gnmi_ext::Extension->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub supported_models {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'supported_models'} = $value;
    }
    return $self->{'supported_models'};
}

sub supported_encodings {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'supported_encodings'} = $value;
    }
    return $self->{'supported_encodings'};
}

sub gNMI_version {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'gNMI_version'} = $value;
    }
    return $self->{'gNMI_version'};
}

sub extension {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'extension'} = $value;
    }
    return $self->{'extension'};
}

} # end package Gnmi::CapabilityResponse

{
package Gnmi::ModelData;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'gnmi.ModelData',
        syntax => 'proto3',
        _class => 'Gnmi::ModelData',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'name',
        json_name => 'name',
        number => 1,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'name'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'name'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'organization',
        json_name => 'organization',
        number => 2,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'organization'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'organization'} = 2;
    $DESCRIPTOR->{fields}{3} = {
        name => 'version',
        json_name => 'version',
        number => 3,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'version'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'version'} = 3;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub name {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'name'} = $value;
    }
    return $self->{'name'};
}

sub organization {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'organization'} = $value;
    }
    return $self->{'organization'};
}

sub version {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'version'} = $value;
    }
    return $self->{'version'};
}

} # end package Gnmi::ModelData

{
package Gnmi::GNMI::Client;
use strict;
use warnings;
use ProtocolBuffers::PP::Encode qw(encode_message);
use ProtocolBuffers::PP::Decode qw(decode_message);

use ProtocolBuffers::PP::GRPC::Call;

sub new {
    my ($class, %args) = @_;
    return bless { channel => $args{channel} }, $class;
}

sub Capabilities {
    my ($self, $request, %opts) = @_;
    my $req_desc = Gnmi::CapabilityRequest->__DESCRIPTOR__;
    my $req_bytes = encode_message($request, $req_desc);
    my $result = $self->{channel}->unary(
        '/gnmi.gNMI/Capabilities', $req_bytes, %opts,
    );
    if (defined $result->{grpc_status} && $result->{grpc_status} != 0) {
        die "gRPC error (status $result->{grpc_status}): "
            . ($result->{grpc_message} // 'unknown') . "\n";
    }
    my $resp_desc = Gnmi::CapabilityResponse->__DESCRIPTOR__;
    return decode_message($resp_desc, $result->{messages}[0], $resp_desc);
}

sub Get {
    my ($self, $request, %opts) = @_;
    my $req_desc = Gnmi::GetRequest->__DESCRIPTOR__;
    my $req_bytes = encode_message($request, $req_desc);
    my $result = $self->{channel}->unary(
        '/gnmi.gNMI/Get', $req_bytes, %opts,
    );
    if (defined $result->{grpc_status} && $result->{grpc_status} != 0) {
        die "gRPC error (status $result->{grpc_status}): "
            . ($result->{grpc_message} // 'unknown') . "\n";
    }
    my $resp_desc = Gnmi::GetResponse->__DESCRIPTOR__;
    return decode_message($resp_desc, $result->{messages}[0], $resp_desc);
}

sub Set {
    my ($self, $request, %opts) = @_;
    my $req_desc = Gnmi::SetRequest->__DESCRIPTOR__;
    my $req_bytes = encode_message($request, $req_desc);
    my $result = $self->{channel}->unary(
        '/gnmi.gNMI/Set', $req_bytes, %opts,
    );
    if (defined $result->{grpc_status} && $result->{grpc_status} != 0) {
        die "gRPC error (status $result->{grpc_status}): "
            . ($result->{grpc_message} // 'unknown') . "\n";
    }
    my $resp_desc = Gnmi::SetResponse->__DESCRIPTOR__;
    return decode_message($resp_desc, $result->{messages}[0], $resp_desc);
}

sub Subscribe {
    my $self = shift;
    my $req_desc = Gnmi::SubscribeRequest->__DESCRIPTOR__;
    my $resp_desc = Gnmi::SubscribeResponse->__DESCRIPTOR__;
    if (ref $_[0] ne 'ARRAY') {
        my %opts = @_;
        return $self->{channel}->streaming_call(
            '/gnmi.gNMI/Subscribe',
            input_descriptor  => $req_desc,
            output_descriptor => $resp_desc,
            on_message        => $opts{on_message},
            on_close          => $opts{on_close},
            on_headers        => $opts{on_headers},
            on_trailers       => $opts{on_trailers},
            timeout           => $opts{timeout},
            headers           => $opts{headers},
        );
    }
    my ($requests, %opts) = @_;
    my @req_bytes = map { encode_message($_, $req_desc) } @$requests;
    my $result = $self->{channel}->bidi_stream(
        '/gnmi.gNMI/Subscribe', \@req_bytes, %opts,
    );
    if (defined $result->{grpc_status} && $result->{grpc_status} != 0) {
        die "gRPC error (status $result->{grpc_status}): "
            . ($result->{grpc_message} // 'unknown') . "\n";
    }
    return [ map { decode_message($resp_desc, $_, $resp_desc) } @{$result->{messages}} ];
}

} # end package Gnmi::GNMI::Client

1;
