# Generated by protoc-gen-perl. DO NOT EDIT.
# Source: conformance/conformance.proto

{
package Conformance::WireFormat;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Enum';

use constant {
    UNSPECIFIED => 0,
    PROTOBUF => 1,
    JSON => 2,
    JSPB => 3,
    TEXT_FORMAT => 4,
};

my %VALUES = (
    'UNSPECIFIED' => 0,
    'PROTOBUF' => 1,
    'JSON' => 2,
    'JSPB' => 3,
    'TEXT_FORMAT' => 4,
);

my %NAMES = reverse %VALUES;

sub _values { \%VALUES }
sub name_for { my ($class, $num) = @_; return $NAMES{$num} }
sub value_for { my ($class, $name) = @_; return $VALUES{$name} }

} # end package Conformance::WireFormat

{
package Conformance::TestCategory;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Enum';

use constant {
    UNSPECIFIED_TEST => 0,
    BINARY_TEST => 1,
    JSON_TEST => 2,
    JSON_IGNORE_UNKNOWN_PARSING_TEST => 3,
    JSPB_TEST => 4,
    TEXT_FORMAT_TEST => 5,
};

my %VALUES = (
    'UNSPECIFIED_TEST' => 0,
    'BINARY_TEST' => 1,
    'JSON_TEST' => 2,
    'JSON_IGNORE_UNKNOWN_PARSING_TEST' => 3,
    'JSPB_TEST' => 4,
    'TEXT_FORMAT_TEST' => 5,
);

my %NAMES = reverse %VALUES;

sub _values { \%VALUES }
sub name_for { my ($class, $num) = @_; return $NAMES{$num} }
sub value_for { my ($class, $name) = @_; return $VALUES{$name} }

} # end package Conformance::TestCategory

{
package Conformance::TestStatus;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'conformance.TestStatus',
        syntax => 'proto3',
        _class => 'Conformance::TestStatus',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'name',
        json_name => 'name',
        number => 1,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'name'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'name'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'failure_message',
        json_name => 'failureMessage',
        number => 2,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'failure_message'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'failureMessage'} = 2;
    $DESCRIPTOR->{fields}{3} = {
        name => 'matched_name',
        json_name => 'matchedName',
        number => 3,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'matched_name'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'matchedName'} = 3;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub name {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'name'} = $value;
    }
    return $self->{'name'};
}

sub failure_message {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'failure_message'} = $value;
    }
    return $self->{'failure_message'};
}

sub matched_name {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'matched_name'} = $value;
    }
    return $self->{'matched_name'};
}

} # end package Conformance::TestStatus

{
package Conformance::FailureSet;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'conformance.FailureSet',
        syntax => 'proto3',
        _class => 'Conformance::FailureSet',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{2} = {
        name => 'test',
        json_name => 'test',
        number => 2,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Conformance::TestStatus',
    };
    $DESCRIPTOR->{fields_by_name}{'test'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'test'} = 2;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{2}{message_descriptor} = Conformance::TestStatus->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub test {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'test'} = $value;
    }
    return $self->{'test'};
}

} # end package Conformance::FailureSet

{
package Conformance::ConformanceRequest;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'conformance.ConformanceRequest',
        syntax => 'proto3',
        _class => 'Conformance::ConformanceRequest',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    push @{$DESCRIPTOR->{oneofs}}, { name => 'payload', fields => [] };
    $DESCRIPTOR->{fields}{1} = {
        name => 'protobuf_payload',
        json_name => 'protobufPayload',
        number => 1,
        type => 12,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'protobuf_payload'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'protobufPayload'} = 1;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'json_payload',
        json_name => 'jsonPayload',
        number => 2,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'json_payload'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'jsonPayload'} = 2;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 2;
    $DESCRIPTOR->{fields}{7} = {
        name => 'jspb_payload',
        json_name => 'jspbPayload',
        number => 7,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'jspb_payload'} = 7;
    $DESCRIPTOR->{fields_by_json_name}{'jspbPayload'} = 7;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 7;
    $DESCRIPTOR->{fields}{8} = {
        name => 'text_payload',
        json_name => 'textPayload',
        number => 8,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'text_payload'} = 8;
    $DESCRIPTOR->{fields_by_json_name}{'textPayload'} = 8;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 8;
    $DESCRIPTOR->{fields}{3} = {
        name => 'requested_output_format',
        json_name => 'requestedOutputFormat',
        number => 3,
        type => 14,
        label => 1,
        packed => 0,
        oneof_index => undef,
        enum_class => 'Conformance::WireFormat',
    };
    $DESCRIPTOR->{fields_by_name}{'requested_output_format'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'requestedOutputFormat'} = 3;
    $DESCRIPTOR->{fields}{4} = {
        name => 'message_type',
        json_name => 'messageType',
        number => 4,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'message_type'} = 4;
    $DESCRIPTOR->{fields_by_json_name}{'messageType'} = 4;
    $DESCRIPTOR->{fields}{5} = {
        name => 'test_category',
        json_name => 'testCategory',
        number => 5,
        type => 14,
        label => 1,
        packed => 0,
        oneof_index => undef,
        enum_class => 'Conformance::TestCategory',
    };
    $DESCRIPTOR->{fields_by_name}{'test_category'} = 5;
    $DESCRIPTOR->{fields_by_json_name}{'testCategory'} = 5;
    $DESCRIPTOR->{fields}{6} = {
        name => 'jspb_encoding_options',
        json_name => 'jspbEncodingOptions',
        number => 6,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Conformance::JspbEncodingConfig',
    };
    $DESCRIPTOR->{fields_by_name}{'jspb_encoding_options'} = 6;
    $DESCRIPTOR->{fields_by_json_name}{'jspbEncodingOptions'} = 6;
    $DESCRIPTOR->{fields}{9} = {
        name => 'print_unknown_fields',
        json_name => 'printUnknownFields',
        number => 9,
        type => 8,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'print_unknown_fields'} = 9;
    $DESCRIPTOR->{fields_by_json_name}{'printUnknownFields'} = 9;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{6}{message_descriptor} = Conformance::JspbEncodingConfig->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub protobuf_payload {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 1;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 1;
        $self->{'protobuf_payload'} = $value;
    }
    return $self->{'protobuf_payload'};
}

sub json_payload {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 2;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 2;
        $self->{'json_payload'} = $value;
    }
    return $self->{'json_payload'};
}

sub jspb_payload {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 7;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 7;
        $self->{'jspb_payload'} = $value;
    }
    return $self->{'jspb_payload'};
}

sub text_payload {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 8;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 8;
        $self->{'text_payload'} = $value;
    }
    return $self->{'text_payload'};
}

sub requested_output_format {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'requested_output_format'} = $value;
    }
    return $self->{'requested_output_format'};
}

sub message_type {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'message_type'} = $value;
    }
    return $self->{'message_type'};
}

sub test_category {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'test_category'} = $value;
    }
    return $self->{'test_category'};
}

sub jspb_encoding_options {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'jspb_encoding_options'} = $value;
    }
    return $self->{'jspb_encoding_options'};
}

sub print_unknown_fields {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'print_unknown_fields'} = $value;
    }
    return $self->{'print_unknown_fields'};
}

} # end package Conformance::ConformanceRequest

{
package Conformance::ConformanceResponse;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'conformance.ConformanceResponse',
        syntax => 'proto3',
        _class => 'Conformance::ConformanceResponse',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    push @{$DESCRIPTOR->{oneofs}}, { name => 'result', fields => [] };
    $DESCRIPTOR->{fields}{1} = {
        name => 'parse_error',
        json_name => 'parseError',
        number => 1,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'parse_error'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'parseError'} = 1;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 1;
    $DESCRIPTOR->{fields}{6} = {
        name => 'serialize_error',
        json_name => 'serializeError',
        number => 6,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'serialize_error'} = 6;
    $DESCRIPTOR->{fields_by_json_name}{'serializeError'} = 6;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 6;
    $DESCRIPTOR->{fields}{9} = {
        name => 'timeout_error',
        json_name => 'timeoutError',
        number => 9,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'timeout_error'} = 9;
    $DESCRIPTOR->{fields_by_json_name}{'timeoutError'} = 9;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 9;
    $DESCRIPTOR->{fields}{2} = {
        name => 'runtime_error',
        json_name => 'runtimeError',
        number => 2,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'runtime_error'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'runtimeError'} = 2;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 2;
    $DESCRIPTOR->{fields}{3} = {
        name => 'protobuf_payload',
        json_name => 'protobufPayload',
        number => 3,
        type => 12,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'protobuf_payload'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'protobufPayload'} = 3;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 3;
    $DESCRIPTOR->{fields}{4} = {
        name => 'json_payload',
        json_name => 'jsonPayload',
        number => 4,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'json_payload'} = 4;
    $DESCRIPTOR->{fields_by_json_name}{'jsonPayload'} = 4;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 4;
    $DESCRIPTOR->{fields}{5} = {
        name => 'skipped',
        json_name => 'skipped',
        number => 5,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'skipped'} = 5;
    $DESCRIPTOR->{fields_by_json_name}{'skipped'} = 5;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 5;
    $DESCRIPTOR->{fields}{7} = {
        name => 'jspb_payload',
        json_name => 'jspbPayload',
        number => 7,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'jspb_payload'} = 7;
    $DESCRIPTOR->{fields_by_json_name}{'jspbPayload'} = 7;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 7;
    $DESCRIPTOR->{fields}{8} = {
        name => 'text_payload',
        json_name => 'textPayload',
        number => 8,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'text_payload'} = 8;
    $DESCRIPTOR->{fields_by_json_name}{'textPayload'} = 8;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 8;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub parse_error {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 1;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 1;
        $self->{'parse_error'} = $value;
    }
    return $self->{'parse_error'};
}

sub serialize_error {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 6;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 6;
        $self->{'serialize_error'} = $value;
    }
    return $self->{'serialize_error'};
}

sub timeout_error {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 9;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 9;
        $self->{'timeout_error'} = $value;
    }
    return $self->{'timeout_error'};
}

sub runtime_error {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 2;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 2;
        $self->{'runtime_error'} = $value;
    }
    return $self->{'runtime_error'};
}

sub protobuf_payload {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 3;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 3;
        $self->{'protobuf_payload'} = $value;
    }
    return $self->{'protobuf_payload'};
}

sub json_payload {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 4;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 4;
        $self->{'json_payload'} = $value;
    }
    return $self->{'json_payload'};
}

sub skipped {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 5;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 5;
        $self->{'skipped'} = $value;
    }
    return $self->{'skipped'};
}

sub jspb_payload {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 7;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 7;
        $self->{'jspb_payload'} = $value;
    }
    return $self->{'jspb_payload'};
}

sub text_payload {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 8;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 8;
        $self->{'text_payload'} = $value;
    }
    return $self->{'text_payload'};
}

} # end package Conformance::ConformanceResponse

{
package Conformance::JspbEncodingConfig;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'conformance.JspbEncodingConfig',
        syntax => 'proto3',
        _class => 'Conformance::JspbEncodingConfig',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'use_jspb_array_any_format',
        json_name => 'useJspbArrayAnyFormat',
        number => 1,
        type => 8,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'use_jspb_array_any_format'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'useJspbArrayAnyFormat'} = 1;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub use_jspb_array_any_format {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'use_jspb_array_any_format'} = $value;
    }
    return $self->{'use_jspb_array_any_format'};
}

} # end package Conformance::JspbEncodingConfig

1;
