# Generated by protoc-gen-perl. DO NOT EDIT.
# Source: test.proto

{
package Test::Color;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Enum';

use constant {
    RED => 0,
    GREEN => 1,
    BLUE => 2,
};

my %VALUES = (
    'RED' => 0,
    'GREEN' => 1,
    'BLUE' => 2,
);

my %NAMES = reverse %VALUES;

sub _values { \%VALUES }
sub name_for { my ($class, $num) = @_; return $NAMES{$num} }
sub value_for { my ($class, $name) = @_; return $VALUES{$name} }

} # end package Test::Color

{
package Test::Inner;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'test.Inner',
        syntax => 'proto3',
        _class => 'Test::Inner',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'value',
        json_name => 'value',
        number => 1,
        type => 5,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'value'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'value'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'label',
        json_name => 'label',
        number => 2,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'label'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'label'} = 2;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'value'} = $value;
    }
    return $self->{'value'};
}

sub label {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'label'} = $value;
    }
    return $self->{'label'};
}

} # end package Test::Inner

{
package Test::Simple::MetadataEntry;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'test.Simple.MetadataEntry',
        syntax => 'proto3',
        _class => 'Test::Simple::MetadataEntry',
        is_map_entry => 1,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'key',
        json_name => 'key',
        number => 1,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'key'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'key'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'value',
        json_name => 'value',
        number => 2,
        type => 5,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'value'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'value'} = 2;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub key {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'key'} = $value;
    }
    return $self->{'key'};
}

sub value {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'value'} = $value;
    }
    return $self->{'value'};
}

} # end package Test::Simple::MetadataEntry

{
package Test::Simple;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'test.Simple',
        syntax => 'proto3',
        _class => 'Test::Simple',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    push @{$DESCRIPTOR->{oneofs}}, { name => 'test_oneof', fields => [] };
    push @{$DESCRIPTOR->{oneofs}}, { name => '_opt_field', fields => [] };
    $DESCRIPTOR->{fields}{1} = {
        name => 'id',
        json_name => 'id',
        number => 1,
        type => 5,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'id'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'id'} = 1;
    $DESCRIPTOR->{fields}{2} = {
        name => 'name',
        json_name => 'name',
        number => 2,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'name'} = 2;
    $DESCRIPTOR->{fields_by_json_name}{'name'} = 2;
    $DESCRIPTOR->{fields}{3} = {
        name => 'active',
        json_name => 'active',
        number => 3,
        type => 8,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'active'} = 3;
    $DESCRIPTOR->{fields_by_json_name}{'active'} = 3;
    $DESCRIPTOR->{fields}{4} = {
        name => 'score',
        json_name => 'score',
        number => 4,
        type => 1,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'score'} = 4;
    $DESCRIPTOR->{fields_by_json_name}{'score'} = 4;
    $DESCRIPTOR->{fields}{5} = {
        name => 'inner',
        json_name => 'inner',
        number => 5,
        type => 11,
        label => 1,
        packed => 0,
        oneof_index => undef,
        message_class => 'Test::Inner',
    };
    $DESCRIPTOR->{fields_by_name}{'inner'} = 5;
    $DESCRIPTOR->{fields_by_json_name}{'inner'} = 5;
    $DESCRIPTOR->{fields}{6} = {
        name => 'tags',
        json_name => 'tags',
        number => 6,
        type => 5,
        label => 3,
        packed => 1,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'tags'} = 6;
    $DESCRIPTOR->{fields_by_json_name}{'tags'} = 6;
    $DESCRIPTOR->{fields}{7} = {
        name => 'items',
        json_name => 'items',
        number => 7,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Test::Inner',
    };
    $DESCRIPTOR->{fields_by_name}{'items'} = 7;
    $DESCRIPTOR->{fields_by_json_name}{'items'} = 7;
    $DESCRIPTOR->{fields}{8} = {
        name => 'color',
        json_name => 'color',
        number => 8,
        type => 14,
        label => 1,
        packed => 0,
        oneof_index => undef,
        enum_class => 'Test::Color',
    };
    $DESCRIPTOR->{fields_by_name}{'color'} = 8;
    $DESCRIPTOR->{fields_by_json_name}{'color'} = 8;
    $DESCRIPTOR->{fields}{9} = {
        name => 'metadata',
        json_name => 'metadata',
        number => 9,
        type => 11,
        label => 3,
        packed => 0,
        oneof_index => undef,
        message_class => 'Test::Simple::MetadataEntry',
        map_entry => {
            key_type => 9,
            value_type => 5,
        },
    };
    $DESCRIPTOR->{fields_by_name}{'metadata'} = 9;
    $DESCRIPTOR->{fields_by_json_name}{'metadata'} = 9;
    $DESCRIPTOR->{fields}{10} = {
        name => 'str_val',
        json_name => 'strVal',
        number => 10,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'str_val'} = 10;
    $DESCRIPTOR->{fields_by_json_name}{'strVal'} = 10;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 10;
    $DESCRIPTOR->{fields}{11} = {
        name => 'int_val',
        json_name => 'intVal',
        number => 11,
        type => 5,
        label => 1,
        packed => 0,
        oneof_index => 0,
    };
    $DESCRIPTOR->{fields_by_name}{'int_val'} = 11;
    $DESCRIPTOR->{fields_by_json_name}{'intVal'} = 11;
    push @{$DESCRIPTOR->{oneofs}[0]{fields}}, 11;
    $DESCRIPTOR->{fields}{12} = {
        name => 'opt_field',
        json_name => 'optField',
        number => 12,
        type => 5,
        label => 1,
        packed => 0,
        oneof_index => 1,
        proto3_optional => 1,
    };
    $DESCRIPTOR->{fields_by_name}{'opt_field'} = 12;
    $DESCRIPTOR->{fields_by_json_name}{'optField'} = 12;
    push @{$DESCRIPTOR->{oneofs}[1]{fields}}, 12;

    # Resolve message_descriptor references
    $DESCRIPTOR->{fields}{5}{message_descriptor} = Test::Inner->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{7}{message_descriptor} = Test::Inner->__DESCRIPTOR__;
    $DESCRIPTOR->{fields}{9}{message_descriptor} = Test::Simple::MetadataEntry->__DESCRIPTOR__;
    return $DESCRIPTOR;
}

sub id {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'id'} = $value;
    }
    return $self->{'id'};
}

sub name {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'name'} = $value;
    }
    return $self->{'name'};
}

sub active {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'active'} = $value;
    }
    return $self->{'active'};
}

sub score {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'score'} = $value;
    }
    return $self->{'score'};
}

sub inner {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'inner'} = $value;
    }
    return $self->{'inner'};
}

sub tags {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'tags'} = $value;
    }
    return $self->{'tags'};
}

sub items {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'items'} = $value;
    }
    return $self->{'items'};
}

sub color {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'color'} = $value;
    }
    return $self->{'color'};
}

sub metadata {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'metadata'} = $value;
    }
    return $self->{'metadata'};
}

sub str_val {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 10;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 10;
        $self->{'str_val'} = $value;
    }
    return $self->{'str_val'};
}

sub int_val {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[0];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 11;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{0} = 11;
        $self->{'int_val'} = $value;
    }
    return $self->{'int_val'};
}

sub opt_field {
    my ($self, $value) = @_;
    if (@_ > 1) {
        my $desc = $self->__DESCRIPTOR__;
        my $oneof = $desc->{oneofs}[1];
        for my $ofn (@{$oneof->{fields}}) {
            next if $ofn == 12;
            my $ofd = $desc->{fields}{$ofn};
            $self->{$ofd->{name}} = undef;
        }
        $self->{_oneof_case} ||= {};
        $self->{_oneof_case}{1} = 12;
        $self->{'opt_field'} = $value;
    }
    return $self->{'opt_field'};
}

} # end package Test::Simple

1;
