# Generated by protoc-gen-perl. DO NOT EDIT.
# Source: postman-echo.proto

{
package HelloRequest;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'HelloRequest',
        syntax => 'proto3',
        _class => 'HelloRequest',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'greeting',
        json_name => 'greeting',
        number => 1,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'greeting'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'greeting'} = 1;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub greeting {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'greeting'} = $value;
    }
    return $self->{'greeting'};
}

} # end package HelloRequest

{
package HelloResponse;
use strict;
use warnings;
use parent 'ProtocolBuffers::Generated::Message';
use ProtocolBuffers::PP::Types;

my $DESCRIPTOR;
sub __DESCRIPTOR__ { _build_descriptor() unless $DESCRIPTOR; return $DESCRIPTOR }

sub _build_descriptor {
    return $DESCRIPTOR if $DESCRIPTOR;
    $DESCRIPTOR = {
        full_name => 'HelloResponse',
        syntax => 'proto3',
        _class => 'HelloResponse',
        is_map_entry => 0,
        fields => {},
        fields_by_name => {},
        fields_by_json_name => {},
        oneofs => [],
    };

    $DESCRIPTOR->{fields}{1} = {
        name => 'reply',
        json_name => 'reply',
        number => 1,
        type => 9,
        label => 1,
        packed => 0,
        oneof_index => undef,
    };
    $DESCRIPTOR->{fields_by_name}{'reply'} = 1;
    $DESCRIPTOR->{fields_by_json_name}{'reply'} = 1;

    # Resolve message_descriptor references
    return $DESCRIPTOR;
}

sub reply {
    my ($self, $value) = @_;
    if (@_ > 1) {
        $self->{'reply'} = $value;
    }
    return $self->{'reply'};
}

} # end package HelloResponse

{
package HelloService::Client;
use strict;
use warnings;
use ProtocolBuffers::PP::Encode qw(encode_message);
use ProtocolBuffers::PP::Decode qw(decode_message);

sub new {
    my ($class, %args) = @_;
    return bless { channel => $args{channel} }, $class;
}

sub SayHello {
    my ($self, $request, %opts) = @_;
    my $req_desc = HelloRequest->__DESCRIPTOR__;
    my $req_bytes = encode_message($request, $req_desc);
    my $result = $self->{channel}->unary(
        '/HelloService/SayHello', $req_bytes, %opts,
    );
    if (defined $result->{grpc_status} && $result->{grpc_status} != 0) {
        die "gRPC error (status $result->{grpc_status}): "
            . ($result->{grpc_message} // 'unknown') . "\n";
    }
    my $resp_desc = HelloResponse->__DESCRIPTOR__;
    return decode_message($resp_desc, $result->{messages}[0], $resp_desc);
}

sub LotsOfReplies {
    my ($self, $request, %opts) = @_;
    my $req_desc = HelloRequest->__DESCRIPTOR__;
    my $req_bytes = encode_message($request, $req_desc);
    my $result = $self->{channel}->server_stream(
        '/HelloService/LotsOfReplies', $req_bytes, %opts,
    );
    if (defined $result->{grpc_status} && $result->{grpc_status} != 0) {
        die "gRPC error (status $result->{grpc_status}): "
            . ($result->{grpc_message} // 'unknown') . "\n";
    }
    my $resp_desc = HelloResponse->__DESCRIPTOR__;
    return [ map { decode_message($resp_desc, $_, $resp_desc) } @{$result->{messages}} ];
}

sub LotsOfGreetings {
    my ($self, $requests, %opts) = @_;
    my $req_desc = HelloRequest->__DESCRIPTOR__;
    my @req_bytes = map { encode_message($_, $req_desc) } @$requests;
    my $result = $self->{channel}->client_stream(
        '/HelloService/LotsOfGreetings', \@req_bytes, %opts,
    );
    if (defined $result->{grpc_status} && $result->{grpc_status} != 0) {
        die "gRPC error (status $result->{grpc_status}): "
            . ($result->{grpc_message} // 'unknown') . "\n";
    }
    my $resp_desc = HelloResponse->__DESCRIPTOR__;
    return decode_message($resp_desc, $result->{messages}[0], $resp_desc);
}

sub BidiHello {
    my ($self, $requests, %opts) = @_;
    my $req_desc = HelloRequest->__DESCRIPTOR__;
    my @req_bytes = map { encode_message($_, $req_desc) } @$requests;
    my $result = $self->{channel}->bidi_stream(
        '/HelloService/BidiHello', \@req_bytes, %opts,
    );
    if (defined $result->{grpc_status} && $result->{grpc_status} != 0) {
        die "gRPC error (status $result->{grpc_status}): "
            . ($result->{grpc_message} // 'unknown') . "\n";
    }
    my $resp_desc = HelloResponse->__DESCRIPTOR__;
    return [ map { decode_message($resp_desc, $_, $resp_desc) } @{$result->{messages}} ];
}

} # end package HelloService::Client

1;
